"""Catalog part 3 — industries 12-16 (see package docstring for the tuple format)."""

INDUSTRIES_12_16 = {
 "hospitality-tourism": ("Hospitality, Tourism & Event Management", "🏨",
  "Create experiences — hotels, food, travel and events that people remember.", [
  ("Hospitality Operations & Hotel Management", "Hotels & Stays", "service people organization polish energy",
   "Run great hotels — from front office to general manager.",
   "Any;Business Studies;English", "BHM/B.Sc Hospitality (IHM via NCHM JEE)",
   "Guest experience;Operations management;Revenue basics;Team leadership", "PMS systems;POS;Excel",
   3, 15, 2, 3, 0.80, 0.15, 0.05, "Metros;Goa;Rajasthan;Global chains",
   "Culinary Arts & Chef Careers;Hospitality Revenue & Front Office;Cruise & Resort Careers"),
  ("Culinary Arts & Chef Careers", "Food & Beverage", "cooking creativity stamina craft passion",
   "Cook professionally — from commis to executive chef to your own kitchen.",
   "Home Science;Any", "BHM/Culinary diplomas (IHM/CTH);Apprenticeship under chefs",
   "Cooking techniques;Kitchen management;Menu design;Food costing", "Professional kitchens;Inventory systems",
   3, 25, 3, 4, 0.80, 0.15, 0.05, "Metros;Tourist hubs;Cruise & abroad",
   "Bakery & Pâtisserie;Restaurant & Café Entrepreneurship;Food Technology"),
  ("Bakery & Pâtisserie", "Food & Beverage", "baking craft precision creativity sweet",
   "Master breads, cakes and desserts — a booming specialty.",
   "Home Science;Chemistry", "Bakery diplomas;BHM + specialization",
   "Baking science;Patisserie techniques;Decoration;Costing", "Ovens & lab tools;Inventory apps",
   3, 12, 2, 3, 0.75, 0.20, 0.10, "All metros;Cafés everywhere",
   "Culinary Arts & Chef Careers;Restaurant & Café Entrepreneurship;Food Technology"),
  ("Travel & Tourism Management", "Travel & Experiences", "travel people planning culture service",
   "Design and sell travel — agencies, OTAs and destination companies.",
   "Geography;English;Any", "BBA Tourism;BTTM;IATA certifications",
   "Itinerary design;Ticketing & GDS;Customer service;Destination knowledge", "GDS (Amadeus);OTA platforms;CRM",
   3, 10, 2, 3, 0.75, 0.30, 0.40, "Delhi;Mumbai;Kochi;Tourist states",
   "Tour Guiding & Experience Design;Adventure Tourism & Ecotourism;Airline & Airport Careers"),
  ("Event Management", "Events", "events organization energy creativity pressure",
   "Produce weddings, concerts and conferences — logistics meets showtime.",
   "Any;Business Studies", "BBA Event Management;Event diplomas;Learning on crews",
   "Event planning;Vendor & budget management;On-ground execution;Client handling", "Project tools;AV & staging",
   3, 20, 2, 3, 0.80, 0.10, 0.10, "Mumbai;Delhi;Goa;Wedding circuits",
   "Wedding Planning;Event & Experiential Marketing;MICE & Exhibition Management"),
  ("Wedding Planning", "Events", "weddings organization creativity people detail",
   "Run India's biggest private events — the big fat wedding industry.",
   "Any;Home Science", "Any degree + event training;Portfolio of events",
   "Concept & décor planning;Vendor networks;Budgeting;Crisis management", "Planning tools;Décor libraries",
   3, 15, 2, 3, 0.75, 0.05, 0.10, "Delhi;Mumbai;Jaipur;Destination venues",
   "Event Management;Hospitality Operations & Hotel Management;Photography"),
  ("Airline & Airport Careers", "Travel & Experiences", "aviation service travel polish energy",
   "Fly and serve — cabin crew, ground services, airport operations.",
   "English;Any", "12th + cabin crew training;Aviation diplomas;BBA Aviation",
   "Passenger service;Safety procedures;Grooming & communication;Operations", "Airport systems;Safety equipment",
   4, 12, 2, 4, 0.75, 0.20, 0.00, "Delhi;Mumbai;All airport cities",
   "Commercial Pilot;Aviation Management;Travel & Tourism Management"),
  ("Cruise & Resort Careers", "Hotels & Stays", "travel service adventure hospitality global",
   "Work the world's cruise lines and island resorts.",
   "Any;English", "BHM/hospitality diplomas + ship recruitment",
   "Guest service;Multi-cultural teamwork;Entertainment & F&B;Ship discipline", "Ship systems;POS",
   5, 15, 2, 3, 0.70, 0.15, 0.00, "At sea;Goa;Global postings",
   "Hospitality Operations & Hotel Management;Merchant Navy;Culinary Arts & Chef Careers"),
  ("Tour Guiding & Experience Design", "Travel & Experiences", "storytelling culture travel people languages",
   "Turn places into stories — guiding and experience businesses.",
   "History;Geography;Languages", "Any degree + Ministry of Tourism guide license",
   "Storytelling;Local history;Group management;Languages", "Booking platforms;Audio systems",
   2, 8, 1, 2, 0.70, 0.10, 0.10, "Heritage & tourist cities",
   "Travel & Tourism Management;Museum & Heritage Education;Adventure Tourism & Ecotourism"),
  ("Adventure Tourism & Ecotourism", "Travel & Experiences", "adventure outdoors nature fitness courage",
   "Lead treks, rafting and wildlife experiences.",
   "Physical Education;Geography;Biology", "Adventure course certifications (NIM/HMI);Any degree",
   "Outdoor leadership;Safety & rescue;Nature interpretation;Trip logistics", "Safety gear;Navigation tools",
   3, 10, 2, 2, 0.75, 0.05, 0.05, "Himalayas;Rishikesh;Northeast;Coasts",
   "Wildlife Conservation;Sports Coaching;Tour Guiding & Experience Design"),
  ("Hospitality Revenue & Front Office", "Hotels & Stays", "numbers service systems analytics hospitality",
   "Price rooms and run the front desk — hospitality's commercial brain.",
   "Mathematics;Business Studies", "BHM + revenue management training",
   "Revenue management;Reservations systems;Guest relations;Upselling", "PMS;Channel managers;Excel",
   4, 12, 2, 2, 0.75, 0.35, 0.30, "Metros;Hotel chains",
   "Hospitality Operations & Hotel Management;Business Analytics;E-commerce Management"),
  ("Restaurant & Café Entrepreneurship", "Food & Beverage", "food entrepreneurship risk creativity hustle",
   "Open and run your own food business.",
   "Home Science;Business Studies", "Any background + FSSAI license;Culinary training helps",
   "Menu & concept design;Unit economics;Team & vendor management;Marketing", "POS;Delivery platforms;Inventory apps",
   0, 40, 3, 4, 0.75, 0.10, 0.05, "Every city",
   "Culinary Arts & Chef Careers;Entrepreneurship & Startups;Bakery & Pâtisserie"),
  ("MICE & Exhibition Management", "Events", "conferences business events organization global",
   "Run the meetings, incentives, conferences and expos industry.",
   "Business Studies;English", "BBA Events/Tourism;Experience on show floors",
   "Exhibition planning;Sponsorship sales;Delegate management;Venue operations", "Registration platforms;CRM",
   4, 12, 2, 2, 0.75, 0.15, 0.20, "Delhi;Mumbai;Hyderabad;Expo hubs",
   "Event Management;Event & Experiential Marketing;Travel & Tourism Management"),
  ("Wellness & Spa Management", "Hotels & Stays", "wellness service calm care hospitality",
   "Run spas and wellness retreats — where hospitality meets health.",
   "Biology;Any", "BHM/wellness diplomas;Ayurveda/spa certifications",
   "Spa operations;Therapy menus;Guest wellness journeys;Retail", "Spa systems;Booking tools",
   3, 10, 2, 2, 0.75, 0.10, 0.10, "Kerala;Goa;Rishikesh;Resorts",
   "Yoga & Mindfulness Instruction;Ayurveda & Integrative Medicine;Hospitality Operations & Hotel Management"),
  ("Food & Beverage Service", "Food & Beverage", "service people polish energy hospitality",
   "Master restaurant service — from steward to F&B director.",
   "Any;English", "BHM/IHM F&B specialization",
   "Service excellence;Beverage knowledge;Team supervision;Guest delight", "POS;Reservation systems",
   3, 10, 1, 2, 0.75, 0.20, 0.05, "Metros;Hotels & fine dining",
   "Hospitality Operations & Hotel Management;Culinary Arts & Chef Careers;Sommelier & Beverage Careers"),
  ("Sommelier & Beverage Careers", "Food & Beverage", "taste craft knowledge luxury service",
   "Become the expert on wine, coffee, tea and spirits.",
   "Chemistry;Any", "Beverage certifications (WSET/SCA);F&B experience",
   "Tasting & pairing;Menu curation;Sourcing;Guest education", "Tasting labs;Inventory tools",
   4, 10, 3, 2, 0.65, 0.10, 0.10, "Metros;Vineyards (Nashik);Specialty cafés",
   "Food & Beverage Service;Culinary Arts & Chef Careers;Retail Management"),
 ]),

 "transport-logistics": ("Transportation, Logistics & Supply Chain", "🚚",
  "Move everything — people, cargo and the supply chains behind every shelf.", [
  ("Supply Chain Management", "Supply Chain", "logistics systems analytics organization efficiency",
   "Orchestrate how products get made and delivered worldwide.",
   "Mathematics;Business Studies;Economics", "BBA/B.Tech + MBA SCM",
   "Demand planning;Inventory optimization;Network design;Analytics", "ERP (SAP);Excel;Planning tools",
   5, 25, 3, 3, 0.85, 0.35, 0.40, "Mumbai;NCR;Bengaluru;Chennai",
   "Logistics & Warehouse Operations;Procurement & Sourcing;Operations Management"),
  ("Logistics & Warehouse Operations", "Supply Chain", "operations organization practical execution systems",
   "Run warehouses and transport fleets — e-commerce's engine room.",
   "Mathematics;Any", "BBA Logistics;Any degree + sector entry",
   "Warehouse management;Fleet coordination;Last-mile planning;KPI management", "WMS;TMS;Scanners & telematics",
   3, 12, 2, 2, 0.85, 0.40, 0.10, "NCR;Mumbai;Bengaluru;Logistics parks",
   "Supply Chain Management;E-commerce Management;Freight Forwarding & Customs"),
  ("Merchant Navy", "Sea & Air", "sea adventure discipline travel machines",
   "Sail the world's cargo fleets — deck or engine side.",
   "Physics;Mathematics", "B.Sc Nautical Science/Marine Engineering + sponsorship",
   "Navigation/Engineering watch;Cargo operations;Safety at sea;Leadership", "Bridge/engine systems;ECDIS",
   8, 40, 3, 3, 0.75, 0.20, 0.00, "At sea;Mumbai;Chennai;Kochi bases",
   "Marine & Naval Engineering;Shipping & Port Management;Cruise & Resort Careers"),
  ("Commercial Pilot", "Sea & Air", "flying precision responsibility travel discipline",
   "Fly passengers and cargo — the flight deck career.",
   "Physics;Mathematics", "12th PCM + CPL (flying school);Cadet programmes",
   "Flying skill;Navigation;Crew resource management;Regulations", "Aircraft systems;Simulators",
   15, 90, 4, 4, 0.75, 0.20, 0.00, "Airline bases;Delhi;Mumbai",
   "Airline & Airport Careers;Aviation Management;Drone Operations & Services"),
  ("Aviation Management", "Sea & Air", "aviation operations business systems coordination",
   "Run airlines and airports from the ground up.",
   "Mathematics;Business Studies", "BBA Aviation;MBA Aviation Management",
   "Airport operations;Airline economics;Scheduling;Safety compliance", "Aviation systems;Excel",
   5, 15, 3, 3, 0.75, 0.25, 0.20, "Delhi;Mumbai;Hyderabad;GMR/Adani hubs",
   "Airline & Airport Careers;Operations Management;Commercial Pilot"),
  ("Railway Careers", "Land Transport", "railways nation systems service stability",
   "Join the world's largest railway — engineering to operations.",
   "Physics;Mathematics", "B.Tech + RRB/UPSC (IRMS);Diploma routes",
   "Train operations;Infrastructure maintenance;Signalling;Safety", "Railway systems;Signalling tech",
   6, 12, 3, 4, 0.75, 0.25, 0.00, "All-India network",
   "Civil Engineering;Urban Mobility & Metro Careers;Defence & Government Exams Careers"),
  ("Urban Mobility & Metro Careers", "Land Transport", "metro cities transport systems planning",
   "Build and run metros and city transport systems.",
   "Physics;Mathematics;Geography", "B.Tech + metro recruitment;Transport planning M.Tech",
   "Metro operations;Transport planning;Rolling stock basics;Passenger systems", "SCADA;AFC systems;Planning tools",
   5, 15, 3, 3, 0.80, 0.25, 0.10, "Delhi;Bengaluru;Mumbai;20+ metro cities",
   "Railway Careers;Urban & Regional Planning;Electrical & Electronics Engineering"),
  ("Procurement & Sourcing", "Supply Chain", "negotiation analysis vendors costs strategy",
   "Buy smart — sourcing strategy for everything companies consume.",
   "Mathematics;Business Studies;Economics", "BBA/B.Tech + SCM specialization",
   "Vendor evaluation;Negotiation;Contract management;Cost analysis", "ERP;e-Procurement;Excel",
   5, 15, 2, 2, 0.80, 0.35, 0.40, "All industrial metros",
   "Supply Chain Management;Operations Management;Contract & Claims Management"),
  ("Shipping & Port Management", "Sea & Air", "ports trade sea logistics operations",
   "Run the ports and shipping lines carrying 90% of world trade.",
   "Mathematics;Economics;Geography", "BBA Shipping/Port Management;Marine backgrounds",
   "Port operations;Chartering;Documentation;Trade compliance", "Port community systems;EDI",
   5, 15, 3, 2, 0.75, 0.30, 0.10, "Mumbai;Chennai;Visakhapatnam;Kochi;Mundra",
   "Merchant Navy;Freight Forwarding & Customs;Supply Chain Management"),
  ("Freight Forwarding & Customs", "Supply Chain", "trade documentation global detail service",
   "Move cargo across borders — forwarding, customs and EXIM.",
   "Economics;English;Mathematics", "Any degree + EXIM/customs certifications",
   "Freight booking;Customs clearance;Incoterms & documentation;Client service", "EDI;ICEGATE;Tracking systems",
   3, 10, 2, 2, 0.80, 0.40, 0.30, "Port & airport cities",
   "Shipping & Port Management;Logistics & Warehouse Operations;E-commerce Management"),
  ("Last-Mile & Quick Commerce", "Land Transport", "delivery speed operations hustle urban",
   "Run the 10-minute economy — dark stores and delivery networks.",
   "Any;Mathematics", "Any degree;Operations entry roles",
   "Hub operations;Rider management;Route optimization;SLA management", "Delivery apps;Dashboards",
   3, 12, 2, 2, 0.85, 0.35, 0.10, "Every metro & tier-2 city",
   "Logistics & Warehouse Operations;E-commerce Management;Operations Management"),
  ("Drone Operations & Services", "Sea & Air", "drones technology emerging outdoors piloting",
   "Fly drones commercially — mapping, delivery, agriculture, film.",
   "Physics;Mathematics", "DGCA drone pilot certificate;Any degree",
   "Drone piloting;Mission planning;Data capture & processing;Regulations", "Drones;GIS;Mapping software",
   3, 12, 2, 2, 0.85, 0.20, 0.30, "All cities;Field projects",
   "Precision Agriculture & AgriTech;Surveying & Geomatics;Photography"),
  ("Fleet & Transport Management", "Land Transport", "vehicles operations organization practical service",
   "Manage bus, truck and cab fleets — uptime is money.",
   "Mathematics;Any", "BBA Logistics;Automobile diplomas",
   "Fleet scheduling;Maintenance planning;Driver management;Telematics", "Telematics;FMS;Excel",
   3, 10, 2, 2, 0.75, 0.35, 0.05, "All cities;Transport corridors",
   "Logistics & Warehouse Operations;Automotive Engineering;Operations Management"),
  ("Cold Chain & Perishables Logistics", "Supply Chain", "logistics food precision systems niche",
   "Move vaccines, dairy and produce without breaking the cold chain.",
   "Physics;Biology;Mathematics", "SCM degrees + cold-chain specialization",
   "Temperature-controlled ops;Compliance;Network design;Monitoring", "Reefer systems;IoT monitoring",
   4, 10, 3, 2, 0.80, 0.30, 0.10, "Agri & pharma corridors",
   "Supply Chain Management;Food Safety & Quality;Pharmacy"),
  ("Air Traffic & Airport Technical Services", "Sea & Air", "aviation precision responsibility systems calm",
   "Guide aircraft safely — ATC and airport technical operations.",
   "Physics;Mathematics", "B.Sc/B.Tech + AAI ATC exam",
   "Air traffic control;Radar operations;Communication protocol;Decision under pressure", "Radar;Comm systems",
   8, 15, 4, 4, 0.75, 0.20, 0.00, "Airport cities nationwide",
   "Aviation Management;Commercial Pilot;Defence & Government Exams Careers"),
  ("Automobile Service & Diagnostics", "Land Transport", "vehicles hands-on practical technical service",
   "Keep India's vehicles running — EV-era service careers.",
   "Physics;Mathematics", "ITI/Diploma Automobile;B.Voc",
   "Diagnostics;EV systems;Service management;Customer advice", "OBD tools;EV platforms;Workshop equipment",
   2, 8, 2, 2, 0.80, 0.30, 0.00, "Every city and town",
   "Automotive Engineering;Fleet & Transport Management;Retail Management"),
 ]),

 "sports-wellness": ("Sports, Fitness & Wellness", "🏅",
  "Play, coach and heal — careers in performance, fitness and wellbeing.", [
  ("Professional Athletics", "Performance", "sports discipline competition fitness dedication",
   "Compete as a professional athlete — with a plan for the career after.",
   "Physical Education;Any", "Sports academies + federation pathways;Sports quota routes",
   "Sport-specific mastery;Training discipline;Competition psychology;Media handling", "Training tech;Video analysis",
   2, 60, 4, 5, 0.60, 0.05, 0.00, "Academies;National camps;Leagues",
   "Sports Coaching;Sports Science & Performance Analysis;Sports Management & Administration"),
  ("Sports Coaching", "Performance", "coaching teaching sports leadership patience",
   "Coach athletes — school teams to elite squads.",
   "Physical Education;Biology", "B.P.Ed;NIS Patiala diplomas;Federation licenses",
   "Coaching methodology;Periodization;Talent development;Team management", "Video analysis;Training apps",
   3, 10, 3, 3, 0.75, 0.05, 0.10, "Academies;Schools;State centres",
   "Professional Athletics;Physical Education Teaching;Sports Science & Performance Analysis"),
  ("Fitness Training", "Fitness", "fitness people energy coaching health",
   "Train bodies and habits — gyms, studios and online.",
   "Physical Education;Biology", "Fitness certifications (ACE/ACSM/K11);B.P.Ed",
   "Exercise programming;Form correction;Client motivation;Nutrition basics", "Fitness apps;Assessment tools",
   3, 15, 1, 3, 0.80, 0.10, 0.50, "Every city;Online",
   "Sports Nutrition;Yoga & Mindfulness Instruction;Sports Physiotherapy & Rehabilitation"),
  ("Yoga & Mindfulness Instruction", "Wellness", "yoga calm teaching health tradition",
   "Teach yoga and meditation — India's wellness export.",
   "Physical Education;Biology;Sanskrit", "Yoga certifications (YCB);B.Sc Yoga;Gurukul training",
   "Asana & pranayama teaching;Anatomy basics;Class design;Therapeutic adaptation", "Studio setups;Online platforms",
   2, 10, 1, 3, 0.80, 0.05, 0.60, "Rishikesh;Metros;Online worldwide",
   "Wellness & Spa Management;Fitness Training;Ayurveda & Integrative Medicine"),
  ("Sports Science & Performance Analysis", "Performance", "science data sports analytics research",
   "Use data and physiology to make athletes faster and injury-free.",
   "Biology;Physics;Mathematics", "B.Sc Sports Science;+ M.Sc",
   "Performance testing;Data analysis;Load monitoring;Reporting to coaches", "GPS trackers;Video analysis;Excel/R",
   4, 12, 3, 3, 0.75, 0.15, 0.30, "National centres;Franchises;Academies",
   "Sports Coaching;Data & Artificial Intelligence;Sports Physiotherapy & Rehabilitation"),
  ("Sports Physiotherapy & Rehabilitation", "Wellness", "rehab care sports hands-on science",
   "Get athletes back on the field — sport-specific physio.",
   "Biology;Physics", "BPT + MPT Sports",
   "Injury assessment;Rehab protocols;On-field care;Return-to-play testing", "Rehab equipment;Assessment tools",
   4, 15, 3, 3, 0.80, 0.05, 0.20, "Franchises;Academies;Clinics",
   "Physiotherapy;Sports Science & Performance Analysis;Fitness Training"),
  ("Sports Nutrition", "Wellness", "nutrition sports science coaching health",
   "Fuel performance — diet plans for athletes and fitness clients.",
   "Biology;Chemistry;Home Science", "B.Sc Nutrition + sports specialization",
   "Performance nutrition;Supplementation science;Meal planning;Athlete education", "Diet software;Body composition tools",
   3, 12, 2, 3, 0.75, 0.15, 0.60, "Metros;Academies;Online",
   "Nutrition & Dietetics;Fitness Training;Sports Science & Performance Analysis"),
  ("Sports Management & Administration", "Business of Sport", "sports business events organization leadership",
   "Run leagues, clubs and federations — the business behind the game.",
   "Business Studies;Physical Education", "BBA/MBA Sports Management",
   "League operations;Sponsorship;Athlete management;Event delivery", "CRM;Event tools;Excel",
   4, 15, 2, 3, 0.75, 0.15, 0.30, "Mumbai;Delhi;Bengaluru;Franchise cities",
   "Sports Marketing & Sponsorship;Event Management;Business Management"),
  ("Sports Marketing & Sponsorship", "Business of Sport", "marketing sports brands partnerships energy",
   "Sell the game — sponsorships, fan engagement, athlete brands.",
   "Business Studies;English", "BBA Marketing + sports industry entry",
   "Sponsorship sales;Fan engagement;Brand activation;Athlete branding", "Social analytics;CRM",
   4, 15, 2, 3, 0.75, 0.20, 0.50, "Mumbai;Delhi;Bengaluru",
   "Sports Management & Administration;Advertising & Brand Management;Influencer & Creator Management"),
  ("Esports & Gaming Careers", "Performance", "gaming esports competition digital community",
   "Compete, cast and build in India's fastest-growing sport.",
   "Any;Computer Science", "No fixed degree — ranked skill + content;Esports management courses",
   "Game mastery;Streaming & casting;Team operations;Community building", "Streaming setups;Gaming rigs",
   2, 40, 3, 5, 0.70, 0.15, 0.80, "Online;Mumbai;Bengaluru",
   "Content Creation & New Media;Game Development;Sports Management & Administration"),
  ("Sports Journalism & Commentary", "Business of Sport", "sports media storytelling voice knowledge",
   "Cover and call the game — writing, broadcast and commentary.",
   "English;Physical Education", "Mass Comm + sports beat;Deep sport knowledge",
   "Match reporting;Commentary craft;Interviews;Stats literacy", "Broadcast systems;Stats platforms",
   3, 15, 3, 4, 0.65, 0.25, 0.40, "Mumbai;Delhi;Event circuits",
   "Journalism;Broadcasting & Anchoring;Content Creation & New Media"),
  ("Physical Education Teaching", "Fitness", "teaching sports children health service",
   "Teach PE — every school needs movement educators.",
   "Physical Education;Biology", "B.P.Ed + school recruitment",
   "PE pedagogy;Sports organization;Child fitness;Safety", "School sports equipment;Assessment apps",
   3, 8, 2, 2, 0.80, 0.05, 0.05, "Every school in India",
   "Teaching (School);Sports Coaching;Fitness Training"),
  ("Adventure Sports Instruction", "Performance", "adventure outdoors courage fitness instruction",
   "Teach climbing, paragliding, scuba — adrenaline as a job.",
   "Physical Education;Geography", "Certifications (NIM/HMI/PADI/SIV)",
   "Technical skill;Safety & rescue;Instruction;Equipment care", "Safety gear;Specialized equipment",
   3, 12, 3, 2, 0.70, 0.05, 0.00, "Himalayas;Goa;Andamans;Rishikesh",
   "Adventure Tourism & Ecotourism;Sports Coaching;Firefighting & Emergency Response"),
  ("Referee & Match Officiating", "Performance", "sports fairness rules decisiveness fitness",
   "Officiate the game — from local leagues to international panels.",
   "Physical Education;Any", "Federation officiating courses + match ladder",
   "Rule mastery;Decision making under pressure;Fitness;Game management", "Officiating tech;Review systems",
   2, 8, 3, 3, 0.65, 0.10, 0.05, "League & federation circuits",
   "Sports Coaching;Sports Management & Administration;Professional Athletics"),
  ("Sports Psychology", "Wellness", "psychology sports mind performance care",
   "Train the mental game — focus, pressure and comebacks.",
   "Psychology;Physical Education", "B.A./B.Sc Psychology + M.Sc Sports Psychology",
   "Mental skills training;Performance counselling;Team dynamics;Assessment", "Assessment tools;Biofeedback",
   4, 10, 3, 3, 0.70, 0.05, 0.50, "National centres;Franchises;Online",
   "Clinical Psychology;Sports Science & Performance Analysis;Counselling Psychology"),
  ("Stadium & Facility Operations", "Business of Sport", "operations venues events practical systems",
   "Run stadiums, arenas and sports complexes.",
   "Any;Physics", "Facility/sports management degrees;Event ops experience",
   "Venue operations;Turf & asset management;Event-day logistics;Safety", "BMS;Turf tech;Ticketing systems",
   4, 8, 2, 2, 0.70, 0.20, 0.05, "Franchise & event cities",
   "Facilities Management;Event Management;Sports Management & Administration"),
 ]),

 "social-impact": ("Social Impact, Psychology & Community Services", "🤝",
  "Heal minds and strengthen communities — psychology, social work and the development sector.", [
  ("Clinical Psychology", "Psychology", "psychology empathy science listening depth",
   "Assess and treat mental illness — the clinician's path.",
   "Psychology;Biology", "B.A./B.Sc Psychology + M.A. + M.Phil Clinical (RCI)",
   "Psychological assessment;Psychotherapy;Case formulation;Ethics", "Assessment batteries;Therapy frameworks",
   4, 25, 4, 4, 0.90, 0.05, 0.50, "Metros;Hospitals;Telehealth",
   "Mental Health & Psychiatry;Counselling Psychology;Neuroscience"),
  ("Counselling Psychology", "Psychology", "listening empathy people guidance care",
   "Counsel people through life's struggles — schools, workplaces, practice.",
   "Psychology;Any", "B.A. Psychology + M.A. Counselling",
   "Counselling skills;Therapeutic techniques;Assessment;Referral judgement", "Counselling frameworks;Teletherapy platforms",
   3, 15, 3, 3, 0.85, 0.05, 0.60, "All cities;Online practice",
   "Clinical Psychology;Career Counselling;Substance Abuse & De-addiction Work"),
  ("Social Work", "Community Practice", "service community empathy fieldwork justice",
   "Professional social work — families, communities, institutions.",
   "Social Science;Any", "BSW + MSW (TISS and others)",
   "Casework;Community organization;Programme delivery;Documentation", "Case systems;Field tools",
   3, 10, 3, 2, 0.80, 0.05, 0.20, "Everywhere;NGOs;Government programmes",
   "NGO & Development Management;Child Welfare & Protection;Community Health Work"),
  ("NGO & Development Management", "Development Sector", "development leadership programs mission organization",
   "Run the organizations solving India's hardest problems.",
   "Social Science;Economics;Any", "Any degree + MA Development/MSW;IRMA/APU/TISS",
   "Programme management;Fundraising;M&E;Team leadership", "MIS;Grant systems;Excel",
   4, 15, 3, 3, 0.80, 0.10, 0.40, "Delhi;Mumbai;Bengaluru;Field districts",
   "Social Work;CSR & Corporate Social Impact;Fundraising & Grant Writing"),
  ("CSR & Corporate Social Impact", "Development Sector", "corporate impact programs strategy partnership",
   "Direct companies' 2% — CSR strategy and programmes.",
   "Business Studies;Social Science", "MBA/MSW + CSR specialization",
   "CSR strategy;Partner selection;Impact measurement;Compliance (Sec 135)", "Impact dashboards;Excel",
   6, 18, 3, 3, 0.80, 0.15, 0.50, "Mumbai;Delhi;Bengaluru",
   "NGO & Development Management;Climate & ESG Careers;Public Policy & Governance"),
  ("Child Welfare & Protection", "Community Practice", "children protection care justice service",
   "Protect childhood — CWCs, adoption, education rights.",
   "Psychology;Social Science", "MSW/child rights specialization;Law helps",
   "Case management;Child-friendly procedure;Family strengthening;Legal coordination", "Case systems;Helpline platforms",
   3, 10, 3, 2, 0.80, 0.05, 0.20, "District child protection units nationwide",
   "Social Work;Special Education;Human Rights & Legal Aid"),
  ("Community Health Work", "Community Practice", "health community service field prevention",
   "Bring healthcare to the last mile — programmes, ASHA systems, NGOs.",
   "Biology;Social Science", "B.Sc/BSW + public health training;MPH for leadership",
   "Health education;Programme delivery;Data collection;Community trust", "mHealth apps;Survey tools",
   3, 10, 3, 2, 0.85, 0.05, 0.10, "Rural & urban-slum programmes nationwide",
   "Public Health;Social Work;Nursing"),
  ("Gerontology & Elder Care", "Community Practice", "elderly care empathy service emerging",
   "Serve India's fastest-growing demographic — elder care services.",
   "Biology;Psychology;Home Science", "Geriatric care diplomas;Nursing/MSW routes",
   "Geriatric care;Care-home operations;Family counselling;Dementia support", "Care management systems;Assistive tech",
   3, 10, 2, 2, 0.85, 0.05, 0.20, "Metros;Kerala;Senior-living hubs",
   "Nursing;Counselling Psychology;Wellness & Spa Management"),
  ("Disaster Relief & Humanitarian Aid", "Development Sector", "crisis courage logistics service resilience",
   "Respond when everything breaks — relief operations and humanitarian work.",
   "Geography;Social Science;Any", "MSW/Disaster Management degrees;NDRF/NGO pathways",
   "Rapid assessment;Relief logistics;Coordination (sphere standards);Field resilience", "GIS;Relief supply systems",
   4, 12, 3, 2, 0.75, 0.05, 0.10, "Deployment-based;Delhi HQs",
   "Disaster Management & Resilience;NGO & Development Management;Firefighting & Emergency Response"),
  ("Fundraising & Grant Writing", "Development Sector", "writing persuasion mission relationships strategy",
   "Fuel the mission — raise the money that change runs on.",
   "English;Economics;Any", "Any degree + fundraising skill;Development studies help",
   "Donor research;Proposal writing;Campaign management;Donor relations", "CRM;Grant portals;Email tools",
   4, 12, 2, 3, 0.80, 0.20, 0.70, "Delhi;Mumbai;Bengaluru;Remote",
   "NGO & Development Management;Content Marketing & Copywriting;CSR & Corporate Social Impact"),
  ("Policy Advocacy & Activism", "Development Sector", "advocacy justice communication courage policy",
   "Change the rules — campaigns, coalitions and public pressure.",
   "Polity;Social Science;English", "Any degree + issue expertise;Law/policy helps",
   "Campaign strategy;Coalition building;Media advocacy;Policy analysis", "Petition platforms;Media tools",
   3, 10, 3, 3, 0.70, 0.05, 0.40, "Delhi;State capitals;Field",
   "Human Rights & Legal Aid;Public Policy & Governance;Journalism"),
  ("Rehabilitation & Disability Services", "Community Practice", "disability inclusion care service dignity",
   "Build an accessible India — rehabilitation and disability services.",
   "Psychology;Biology", "Rehabilitation Council (RCI) degrees;MSW Disability",
   "Disability assessment;Rehab planning;Assistive technology;Advocacy", "Assistive tech;Therapy tools",
   3, 10, 3, 2, 0.80, 0.05, 0.20, "District disability centres;NGOs",
   "Occupational Therapy;Special Education;Social Work"),
  ("Substance Abuse & De-addiction Work", "Psychology", "addiction counselling care resilience health",
   "Help people out of addiction — counselling and programme work.",
   "Psychology;Biology", "M.A. Psychology/MSW + de-addiction specialization",
   "Addiction counselling;Relapse prevention;Family therapy;Group facilitation", "Screening tools;Therapy frameworks",
   3, 10, 3, 2, 0.75, 0.05, 0.30, "De-addiction centres nationwide",
   "Counselling Psychology;Clinical Psychology;Community Health Work"),
  ("Organizational Psychology", "Psychology", "psychology workplace people research analytics",
   "Apply psychology to work — hiring science, culture, performance.",
   "Psychology;Mathematics", "B.A. Psychology + M.A. I/O Psychology",
   "Psychometric assessment;Culture research;Intervention design;People analytics", "Assessment platforms;R/SPSS",
   6, 15, 3, 3, 0.80, 0.15, 0.70, "Bengaluru;Mumbai;Gurugram",
   "Human Resources;Consumer Psychology;Counselling Psychology"),
  ("Social Entrepreneurship", "Development Sector", "entrepreneurship impact innovation mission grit",
   "Build ventures where profit and purpose compound.",
   "Any;Economics;Social Science", "Any degree + venture;Fellowships (Ashoka/Acumen)",
   "Impact business models;Fundraising (blended);Community co-creation;Storytelling", "No-code tools;Impact metrics",
   0, 60, 4, 4, 0.75, 0.05, 0.50, "Bengaluru;Field geographies",
   "Entrepreneurship & Startups;NGO & Development Management;Waste Management & Circular Economy"),
  ("Social Research & Sociology", "Psychology", "research society data fieldwork curiosity",
   "Study society itself — surveys, ethnography, evaluation.",
   "Social Science;Mathematics", "B.A. Sociology/Economics + M.A.;Research org entry",
   "Survey design;Qualitative methods;Statistical analysis;Report writing", "Survey CAPI tools;R/SPSS/Stata",
   4, 12, 3, 2, 0.75, 0.15, 0.50, "Delhi;Mumbai;Research orgs",
   "Market Research & Insights;Economics & Policy Analysis;Public Policy & Governance"),
  ("Counselling for Schools (School Counsellor)", "Psychology", "children listening school guidance care",
   "Be the trusted adult every school needs.",
   "Psychology;Education", "B.A./M.A. Psychology + school counselling certification",
   "Student counselling;Crisis response;Parent-teacher collaboration;Referrals", "Counselling tools;Screeners",
   3, 10, 2, 2, 0.85, 0.05, 0.20, "Schools everywhere",
   "Counselling Psychology;Career Counselling;Educational Psychology"),
  ("Museum, Culture & Community Programs", "Community Practice", "culture community programs creativity education",
   "Run community culture — libraries, museums, maker spaces, festivals.",
   "History;Arts;Social Science", "B.A. + cultural management;Museology",
   "Program design;Community engagement;Grant management;Partnerships", "Event tools;Community platforms",
   3, 8, 2, 2, 0.65, 0.05, 0.30, "Metros;Culture cities",
   "Museum & Heritage Education;Event Management;NGO & Development Management"),
 ]),

 "defence-security": ("Defence, Security & Emergency Services", "🛡️",
  "Protect the nation and its people — armed forces, police, intelligence and emergency response.", [
  ("Army Officer", "Armed Forces", "service courage leadership discipline nation",
   "Lead soldiers — India's largest and most respected officer corps.",
   "Any;Physics;Mathematics", "NDA after 12th;CDS after degree;TES/TGC technical entries",
   "Leadership under pressure;Tactics;Physical fitness;Man management", "Military systems;Communications",
   9, 25, 3, 4, 0.80, 0.05, 0.00, "All-India postings;Border areas",
   "Navy Officer;Air Force Officer;Paramilitary & Central Armed Police"),
  ("Navy Officer", "Armed Forces", "sea service courage discipline technology",
   "Command at sea — warships, submarines, naval aviation.",
   "Physics;Mathematics", "NDA;CDS;INET;10+2 B.Tech Cadet Entry",
   "Seamanship;Navigation;Warfare systems;Leadership", "Naval combat systems;Navigation tech",
   9, 25, 3, 4, 0.75, 0.05, 0.00, "Mumbai;Visakhapatnam;Kochi;At sea",
   "Army Officer;Merchant Navy;Coast Guard"),
  ("Air Force Officer", "Armed Forces", "flying service courage precision technology",
   "Fly and fight — fighters, transports, helicopters; plus ground branches.",
   "Physics;Mathematics", "NDA;CDS;AFCAT",
   "Airmanship;Systems operation;Decision speed;Leadership", "Aircraft;Radar;Mission systems",
   9, 30, 4, 4, 0.75, 0.05, 0.00, "Air bases nationwide",
   "Commercial Pilot;Army Officer;Aerospace Engineering"),
  ("Paramilitary & Central Armed Police", "Armed Forces", "service security discipline courage nation",
   "Guard borders and critical assets — BSF, CRPF, CISF, ITBP, SSB.",
   "Any;Physical Education", "CAPF Assistant Commandant exam;Constable/SI entries",
   "Security operations;Border management;Crowd control;Leadership", "Security equipment;Surveillance",
   6, 15, 2, 4, 0.80, 0.05, 0.00, "Borders;Airports;Installations",
   "Army Officer;Police Services;Private Security & Corporate Protection"),
  ("Police Services", "Policing & Investigation", "law-enforcement service courage justice community",
   "Keep the peace — from constable to IPS.",
   "Any;Polity;Physical Education", "State police exams;UPSC (IPS)",
   "Investigation;Law & procedure;Community policing;Crisis handling", "CCTNS;Forensic liaison;Communication",
   4, 15, 3, 4, 0.80, 0.05, 0.00, "Every district",
   "Civil Services (IAS/IPS/IFS);Crime Scene Investigation;Paramilitary & Central Armed Police"),
  ("Intelligence & Investigation Agencies", "Policing & Investigation", "intelligence analysis secrecy nation vigilance",
   "Work the shadows — IB, R&AW, NIA, ED analyst and officer roles.",
   "Any;Polity;Languages", "Graduate + agency exams (ACIO etc.);Deputation routes",
   "Intelligence analysis;Surveillance craft;Report writing;Languages", "OSINT tools;Analysis platforms",
   6, 15, 4, 4, 0.75, 0.10, 0.05, "Delhi;Sensitive postings",
   "Police Services;Defence Cyber Operations;Crime Scene Investigation"),
  ("Defence Cyber Operations", "Security Technology", "cyber defence security technology vigilance",
   "Defend national networks — military and agency cyber units.",
   "Computer Science;Mathematics;Physics", "B.Tech + defence entries;Agency cyber recruitment",
   "Cyber defence;Threat hunting;Digital forensics;Secure systems", "SOC platforms;Forensic tools",
   7, 20, 4, 3, 0.85, 0.15, 0.20, "Delhi;Service HQs",
   "Cybersecurity;Intelligence & Investigation Agencies;Software Engineering"),
  ("Crime Scene Investigation", "Policing & Investigation", "forensics detail investigation science justice",
   "Process crime scenes — evidence collection and forensic liaison.",
   "Chemistry;Biology;Physics", "B.Sc Forensic Science + FSL/police recruitment",
   "Scene processing;Evidence handling;Documentation;Court testimony", "Evidence kits;Photography;Lab liaison",
   4, 12, 3, 3, 0.75, 0.15, 0.05, "State FSLs;District units",
   "Forensic Science;Police Services;Criminal Law"),
  ("Firefighting & Emergency Response", "Emergency Services", "courage rescue service fitness calm",
   "Run toward the fire — municipal and industrial emergency response.",
   "Physics;Chemistry;Physical Education", "Fire engineering diplomas (NFSC);State fire services",
   "Fire suppression;Rescue techniques;Hazmat handling;Drill discipline", "Fire apparatus;Rescue tools;BA sets",
   3, 10, 3, 3, 0.80, 0.10, 0.00, "Every city;Industrial plants;Airports",
   "Disaster Management & Resilience;Paramedical & Emergency Care;Site Supervision & Safety (EHS)"),
  ("Disaster Management & Resilience", "Emergency Services", "disaster planning coordination service systems",
   "Prepare cities and states for the worst — NDMA/SDMA careers.",
   "Geography;Social Science;Any", "Disaster Management degrees;MPA/MSW routes",
   "Risk assessment;Response planning;Inter-agency coordination;Community preparedness", "GIS;Early-warning systems",
   4, 12, 3, 2, 0.80, 0.10, 0.20, "Delhi;State capitals;District units",
   "Disaster Relief & Humanitarian Aid;Firefighting & Emergency Response;Urban Governance & Administration"),
  ("Defence Research & Development", "Security Technology", "research defence technology science nation",
   "Build India's defence tech — DRDO, defence PSUs and private defence.",
   "Physics;Mathematics;Chemistry", "B.Tech/M.Sc + DRDO SET/GATE;PhD for scientist roles",
   "Applied R&D;Systems testing;Documentation;Security discipline", "Lab & test ranges;Simulation",
   7, 20, 4, 3, 0.80, 0.10, 0.10, "Delhi;Hyderabad;Bengaluru;Pune",
   "Aerospace Engineering;Space Science & Careers;Electronics & Communication Engineering"),
  ("Coast Guard", "Armed Forces", "sea rescue service courage vigilance",
   "Guard the coast — search & rescue, anti-smuggling, pollution response.",
   "Physics;Mathematics", "Indian Coast Guard entries (Navik/Assistant Commandant)",
   "Maritime operations;Search & rescue;Boarding operations;Seamanship", "Patrol vessels;Sensors",
   6, 15, 3, 3, 0.75, 0.05, 0.00, "Coastal stations nationwide",
   "Navy Officer;Merchant Navy;Firefighting & Emergency Response"),
  ("Private Security & Corporate Protection", "Security Services", "security operations vigilance management service",
   "Protect people and assets — corporate security and executive protection.",
   "Any;Physical Education", "Any degree + PSARA/security management;Ex-forces preferred",
   "Threat assessment;Security operations;Team management;Emergency procedure", "Surveillance systems;Access control",
   4, 12, 2, 2, 0.75, 0.20, 0.05, "All metros;Industrial sites",
   "Paramilitary & Central Armed Police;Facilities Management;Risk & Security Consulting"),
  ("Risk & Security Consulting", "Security Services", "risk analysis strategy security corporate",
   "Advise companies on risk — investigations, integrity, resilience.",
   "Any;Economics;Polity", "Any degree + risk certifications;Big-4 forensics entry",
   "Risk assessment;Corporate investigation;Due diligence;Crisis planning", "Analytics tools;Case platforms",
   6, 18, 3, 3, 0.75, 0.20, 0.50, "Mumbai;Delhi;Bengaluru",
   "Legal Compliance & Governance;Cybersecurity;Private Security & Corporate Protection"),
  ("Aviation & Transport Security", "Security Services", "security aviation vigilance procedure service",
   "Secure airports, ports and metros — specialized security careers.",
   "Any;Physics", "CISF/BCAS screener certifications;Security degrees",
   "Screening procedure;Threat detection;Incident response;Passenger handling", "X-ray scanners;ETDs;CCTV",
   3, 10, 2, 3, 0.75, 0.25, 0.00, "Airports;Metros;Ports",
   "Paramilitary & Central Armed Police;Airline & Airport Careers;Private Security & Corporate Protection"),
  ("Military Engineering & Technical Services", "Security Technology", "engineering defence infrastructure discipline technical",
   "Build and maintain what the forces run on — MES, EME, Signals.",
   "Physics;Mathematics", "B.Tech + technical entry (TGC/SSC Tech);MES recruitment",
   "Military infrastructure;Equipment maintenance;Signals & IT;Project execution", "Military-grade systems;CAD",
   7, 15, 3, 3, 0.75, 0.15, 0.05, "Cantonments & commands nationwide",
   "Army Officer;Civil Engineering;Electronics & Communication Engineering"),
 ]),
}
