"""Catalog part 2 — industries 7-11 (see package docstring for the tuple format)."""

INDUSTRIES_7_11 = {
 "law-government": ("Law, Government & Public Policy", "⚖️",
  "Write the rules, argue the cases and run the state — careers in law, governance and policy.", [
  ("Civil Services (IAS/IPS/IFS)", "Government Services", "service leadership administration nation discipline",
   "Run districts, police forces and embassies — India's most powerful public careers.",
   "Any;History;Polity", "Any bachelor's degree + UPSC Civil Services Exam",
   "Administration;Decision making;Public communication;Law & policy knowledge", "e-Governance systems;Office tools",
   10, 25, 5, 5, 0.80, 0.05, 0.05, "All-India postings;Delhi",
   "Public Policy & Governance;Police Services;Diplomacy & International Relations"),
  ("Litigation & Advocacy", "Legal Practice", "argument justice communication research resilience",
   "Argue cases in court — the classic advocate's path.",
   "English;Polity;History", "5-year BA LLB (via CLAT) or 3-year LLB;Bar Council enrolment",
   "Legal research;Drafting;Oral argument;Client counselling", "Legal databases;Case management",
   3, 60, 4, 5, 0.75, 0.15, 0.20, "Delhi;Mumbai;State High Court cities",
   "Judiciary & Judicial Services;Corporate Law;Criminal Law"),
  ("Corporate Law", "Legal Practice", "business law detail negotiation analytical",
   "Advise companies on deals, contracts and compliance.",
   "English;Economics;Polity", "BA LLB (CLAT);+ CS/LLM helpful",
   "Contract drafting;Due diligence;M&A support;Regulatory advice", "Legal databases;Document automation",
   8, 60, 4, 5, 0.80, 0.30, 0.50, "Mumbai;Delhi;Bengaluru;Gurugram",
   "Litigation & Advocacy;Taxation & Corporate Law;Legal Compliance & Governance"),
  ("Judiciary & Judicial Services", "Legal Practice", "justice integrity analytical discipline law",
   "Become a judge through the state judicial services exams.",
   "English;Polity;History", "LLB + State Judicial Services Exam",
   "Legal reasoning;Case analysis;Judgment writing;Court administration", "Court systems;Legal databases",
   8, 15, 5, 5, 0.75, 0.05, 0.05, "All states;District courts upward",
   "Litigation & Advocacy;Civil Services (IAS/IPS/IFS);Criminal Law"),
  ("Criminal Law", "Legal Practice", "justice investigation argument courage law",
   "Prosecute or defend in criminal courts.",
   "English;Polity", "BA LLB;criminal practice apprenticeship",
   "Criminal procedure;Evidence analysis;Cross-examination;Advocacy", "Legal databases;Forensic reports",
   3, 40, 4, 4, 0.70, 0.10, 0.10, "All court cities",
   "Litigation & Advocacy;Crime Scene Investigation;Judiciary & Judicial Services"),
  ("Intellectual Property Law", "Legal Practice", "innovation law detail technology analytical",
   "Protect inventions, brands and creative works.",
   "English;Science background helps", "LLB + IP specialization;Science/Engineering + LLB (patents)",
   "Patent & trademark filing;IP litigation;Licensing;Search & analysis", "IP databases;Filing systems",
   6, 30, 4, 3, 0.75, 0.25, 0.60, "Delhi;Mumbai;Bengaluru",
   "Corporate Law;Technology Law & Cyber Law;Pharmaceutical Research"),
  ("Technology Law & Cyber Law", "Legal Practice", "technology law privacy emerging analytical",
   "Regulate the digital world — data protection, AI law, platform rules.",
   "English;Computer Science helps", "LLB + tech-law specialization",
   "Data protection law;Cybercrime procedure;Tech contracts;Policy analysis", "Legal databases;Compliance tools",
   6, 30, 4, 3, 0.85, 0.20, 0.70, "Delhi;Bengaluru;Mumbai",
   "Cybersecurity;Corporate Law;Public Policy & Governance"),
  ("Taxation & Corporate Law", "Legal Practice", "tax law numbers detail analytical",
   "Master the law of taxes — always in demand, never boring at scale.",
   "Economics;Accountancy;English", "LLB + tax specialization;CA + LLB (powerful combo)",
   "Tax advisory;Appeals & representation;Structuring;Compliance", "Tax portals;Legal databases",
   6, 30, 4, 3, 0.80, 0.30, 0.40, "Mumbai;Delhi;Ahmedabad",
   "Auditing & Taxation;Corporate Law;Chartered Accountancy"),
  ("Legal Compliance & Governance", "Legal Practice", "rules detail integrity process corporate",
   "Keep companies inside the lines — compliance is a fast-growing profession.",
   "English;Economics;Polity", "LLB;CS (Company Secretary);BBA + LLB",
   "Regulatory mapping;Policy drafting;Audits & reporting;Board support", "GRC tools;Compliance systems",
   6, 25, 3, 3, 0.85, 0.35, 0.60, "Mumbai;Delhi;Bengaluru",
   "Corporate Law;Auditing & Taxation;Risk & Security Consulting"),
  ("Public Policy & Governance", "Policy & Public Affairs", "policy research systems service analytical",
   "Design and evaluate the policies that govern a billion people.",
   "Polity;Economics;Social Science", "Any degree + MPP/MPA;Economics/Law background helps",
   "Policy analysis;Program design;Stakeholder consultation;Evidence synthesis", "Excel;Survey tools;Policy briefs",
   6, 25, 3, 3, 0.75, 0.10, 0.50, "Delhi;State capitals;Think tanks",
   "Civil Services (IAS/IPS/IFS);Economics & Policy Analysis;Education Policy"),
  ("Diplomacy & International Relations", "Policy & Public Affairs", "global culture language negotiation service",
   "Represent India abroad — foreign service, international organizations.",
   "History;Polity;Languages", "Any degree + UPSC (IFS);IR Masters for multilateral roles",
   "Negotiation;Political analysis;Protocol;Languages", "Diplomatic systems;Research databases",
   10, 20, 5, 5, 0.70, 0.05, 0.10, "Delhi;World capitals",
   "Civil Services (IAS/IPS/IFS);Public Policy & Governance;Translation & Interpretation"),
  ("Human Rights & Legal Aid", "Policy & Public Affairs", "justice service empathy courage advocacy",
   "Lawyer for those who can't afford one — rights, legal aid, PILs.",
   "Polity;English;Social Science", "LLB;human rights LLM helps",
   "Rights litigation;Field investigation;Documentation;Advocacy", "Legal databases;Case systems",
   3, 15, 3, 2, 0.65, 0.05, 0.20, "Delhi;State capitals;Field areas",
   "Litigation & Advocacy;Policy Advocacy & Activism;Social Work"),
  ("Legislative & Political Careers", "Policy & Public Affairs", "politics communication strategy public leadership",
   "Work inside politics — legislative research, campaigns, political consulting.",
   "Polity;History;Economics", "Any degree;LAMP fellowship;Political science helps",
   "Political research;Speech & brief writing;Campaign strategy;Data analysis", "Survey tools;Social analytics",
   4, 20, 3, 4, 0.70, 0.10, 0.40, "Delhi;State capitals",
   "Public Policy & Governance;Market Research & Insights;Journalism"),
  ("Urban Governance & Administration", "Government Services", "cities administration systems service planning",
   "Run India's cities — municipal services, smart-city programmes.",
   "Polity;Geography;Economics", "Any degree + state PSC;B.Plan/MPA helps",
   "Municipal administration;Service delivery;Project monitoring;Citizen engagement", "e-Governance;GIS basics",
   5, 15, 3, 3, 0.75, 0.15, 0.10, "All cities",
   "Urban & Regional Planning;Civil Services (IAS/IPS/IFS);Public Policy & Governance"),
  ("Legal Process & Research Services", "Legal Practice", "research writing detail law process",
   "Legal research, drafting and process work for global firms — law's back office.",
   "English;Polity", "LLB;B.A. + paralegal training",
   "Legal research;Document review;Contract abstraction;Citation work", "Review platforms;Legal databases",
   4, 15, 2, 3, 0.70, 0.50, 0.80, "Gurugram;Pune;Mumbai;Bengaluru",
   "Corporate Law;Legal Compliance & Governance;Technical Writing"),
  ("Defence & Government Exams Careers", "Government Services", "service discipline stability nation exams",
   "SSC, banking, railways, state services — the exam-driven government pathway.",
   "Any;Quantitative Aptitude", "Any degree + SSC/Banking/Railway/State exams",
   "Exam preparation;General awareness;Quantitative & reasoning skill;Office procedures", "Office systems;e-Governance",
   4, 10, 2, 5, 0.75, 0.25, 0.05, "All-India postings",
   "Civil Services (IAS/IPS/IFS);Banking & Financial Services;Police Services"),
  ("Notary, Registration & Documentation", "Legal Practice", "documents detail service local law",
   "The paperwork backbone of property, marriage and business law.",
   "English;Polity", "LLB + notary appointment;Licensed deed writers",
   "Deed drafting;Verification;Registration procedure;Client service", "Registration portals;Templates",
   3, 8, 2, 2, 0.60, 0.40, 0.05, "Every district",
   "Litigation & Advocacy;Real Estate & Property Management"),
 ]),

 "arts-design-media": ("Arts, Design & Creative Media", "🎨",
  "Make things people feel — visual design, film, music, fashion and storytelling.", [
  ("Graphic Design & Visual Communication", "Design", "creative visual design communication detail",
   "Design the posters, brands and interfaces the world sees every day.",
   "Art;Computer Science;English", "B.Des Communication Design;BFA;Any degree + portfolio",
   "Typography;Layout & composition;Brand identity;Visual storytelling", "Photoshop;Illustrator;Figma;Canva",
   3, 25, 2, 4, 0.75, 0.40, 0.85, "Mumbai;Bengaluru;Delhi;Remote",
   "UX & Interaction Design;Animation & VFX;Art Direction & Advertising"),
  ("Animation & VFX", "Screen & Media", "creative visual storytelling patience craft",
   "Animate films, games and ads — India is a global VFX hub.",
   "Art;Computer Science;Physics", "B.Des Animation;BFA;Diploma + strong showreel",
   "2D/3D animation;Compositing;Modelling & rigging;Storyboarding", "Maya;Blender;After Effects;Nuke",
   3, 30, 3, 4, 0.80, 0.35, 0.60, "Mumbai;Hyderabad;Bengaluru;Chennai",
   "Game Development;Film Making & Direction;Graphic Design & Visual Communication"),
  ("Film Making & Direction", "Screen & Media", "storytelling creative leadership vision persistence",
   "Direct and produce films, series and documentaries.",
   "English;Art;Any", "FTII/SRFTI;Mass Communication;Learning on sets",
   "Visual storytelling;Direction;Screenwriting;Production management", "Cameras;Editing suites;Production tools",
   2, 60, 4, 5, 0.65, 0.15, 0.30, "Mumbai;Hyderabad;Chennai;Kochi",
   "Video Editing & Post-Production;Photography;Acting & Theatre"),
  ("Video Editing & Post-Production", "Screen & Media", "craft visual detail storytelling patience",
   "Cut raw footage into films, reels and shows — every screen needs editors.",
   "Art;Computer Science", "Diploma/degree in editing;Any degree + showreel",
   "Editing rhythm;Colour grading;Sound sync;Delivery formats", "Premiere Pro;DaVinci;Final Cut;After Effects",
   3, 20, 2, 4, 0.85, 0.40, 0.85, "Mumbai;All metros;Remote",
   "Film Making & Direction;Content Creation & New Media;Animation & VFX"),
  ("Photography", "Visual Arts", "visual creative observation independence craft",
   "Tell stories in single frames — weddings to wildlife to editorial.",
   "Art;Physics;Any", "Any degree + portfolio;Photography diplomas",
   "Composition;Lighting;Editing;Client management", "DSLR/mirrorless;Lightroom;Photoshop",
   2, 25, 2, 4, 0.65, 0.30, 0.50, "All cities;Travel-based",
   "Video Editing & Post-Production;Content Creation & New Media;Journalism"),
  ("Fashion Design", "Design", "fashion creative aesthetic craft trends",
   "Design clothing and accessories — from couture to mass market.",
   "Art;Home Science;Business Studies", "B.Des Fashion (NIFT/NID);Fashion diplomas",
   "Garment design;Pattern making;Textile knowledge;Trend research", "Illustrator;CAD;Draping tools",
   3, 30, 3, 4, 0.70, 0.25, 0.30, "Mumbai;Delhi;Bengaluru;Surat",
   "Textile & Craft Design;Retail Management;Jewellery & Accessory Design"),
  ("Interior & Spatial Design", "Design", "space aesthetic creative detail practical",
   "Design the insides of homes, offices and experiences.",
   "Art;Mathematics;Physics", "B.Des Interior;B.Arch;Diplomas + portfolio",
   "Space planning;Material selection;3D visualization;Client presentation", "SketchUp;AutoCAD;V-Ray;3ds Max",
   3, 22, 2, 3, 0.75, 0.20, 0.40, "All metros;Growing tier-2 demand",
   "Architecture;Furniture & Product Design;Real Estate Development"),
  ("Product & Industrial Design", "Design", "creative engineering aesthetics usability building",
   "Design physical products — from appliances to furniture to vehicles.",
   "Art;Physics;Mathematics", "B.Des Industrial (NID/IIT);M.Des",
   "Design thinking;3D modelling;Prototyping;Ergonomics", "Fusion 360;Rhino;KeyShot;3D printing",
   4, 20, 3, 3, 0.75, 0.25, 0.50, "Bengaluru;Pune;Mumbai;NCR",
   "Furniture & Product Design;UX & Interaction Design;Mechanical Engineering"),
  ("Furniture & Product Design", "Design", "craft creative practical materials aesthetic",
   "Design and make furniture and lifestyle products.",
   "Art;Mathematics", "B.Des;Craft-school programmes;Apprenticeship",
   "Material craft;CAD;Manufacturing methods;Finish & detail", "CAD;Workshop tools;CNC",
   3, 12, 2, 2, 0.65, 0.25, 0.30, "Jodhpur;Bengaluru;NCR;Kerala",
   "Product & Industrial Design;Interior & Spatial Design;Textile & Craft Design"),
  ("Music Production & Performance", "Performing Arts", "music creative performance dedication artistry",
   "Compose, produce and perform — from film scores to independent releases.",
   "Music;Any", "Music degrees/gurukuls;Production courses;Portfolio",
   "Composition;Production & mixing;Instrument/vocal mastery;Stagecraft", "DAWs (Logic/Ableton);MIDI;Studio gear",
   2, 40, 3, 5, 0.65, 0.25, 0.70, "Mumbai;Chennai;Delhi;Online",
   "Sound Engineering;Content Creation & New Media;Film Making & Direction"),
  ("Sound Engineering", "Screen & Media", "audio technical detail music craft",
   "Engineer the sound of films, music and live events.",
   "Physics;Music;Mathematics", "Sound engineering diplomas/degrees",
   "Recording;Mixing & mastering;Live sound;Acoustics", "Pro Tools;Consoles;Microphones",
   3, 15, 3, 3, 0.70, 0.30, 0.40, "Mumbai;Chennai;Hyderabad",
   "Music Production & Performance;Film Making & Direction;Event Management"),
  ("Acting & Theatre", "Performing Arts", "performance expression courage empathy resilience",
   "Perform on stage and screen.",
   "English;Any", "NSD/FTII;Theatre groups;Workshops + auditions",
   "Acting technique;Voice & movement;Script analysis;Auditioning", "Self-tape setups;Casting platforms",
   1, 50, 3, 5, 0.60, 0.10, 0.20, "Mumbai;Delhi;Regional film cities",
   "Film Making & Direction;Dance & Choreography;Broadcasting & Anchoring"),
  ("Dance & Choreography", "Performing Arts", "dance performance discipline expression fitness",
   "Perform and choreograph — classical, contemporary, commercial.",
   "Physical Education;Music;Any", "Dance degrees/gharana training;Portfolio & performances",
   "Technique;Choreography;Teaching;Performance fitness", "Studio spaces;Video tools",
   1, 30, 3, 4, 0.60, 0.05, 0.30, "Mumbai;Delhi;Chennai;Online teaching",
   "Acting & Theatre;Fitness Training;Content Creation & New Media"),
  ("Writing & Publishing", "Storytelling", "writing storytelling language imagination discipline",
   "Write books, scripts and stories — and the editing world around them.",
   "English;Literature;Any", "Any degree;M.A. English/Creative Writing helps",
   "Storycraft;Editing;Publishing process;Self-promotion", "Writing software;Publishing platforms",
   2, 25, 3, 4, 0.60, 0.30, 0.90, "Delhi;Mumbai;Anywhere",
   "Journalism;Content Marketing & Copywriting;Screenwriting for OTT"),
  ("Screenwriting for OTT", "Storytelling", "storytelling writing screen drama imagination",
   "Write the series and films streaming platforms are hungry for.",
   "English;Literature", "Any degree + scripts;FTII screenwriting;Writers' rooms",
   "Screenplay structure;Dialogue;Pitching;Rewriting", "Final Draft;Celtx",
   3, 35, 3, 4, 0.75, 0.25, 0.80, "Mumbai;Remote writers' rooms",
   "Writing & Publishing;Film Making & Direction;Content Creation & New Media"),
  ("Fine Arts & Illustration", "Visual Arts", "art creative expression craft patience",
   "Paint, illustrate and exhibit — fine art and commercial illustration.",
   "Art;Any", "BFA;Portfolio-first careers",
   "Drawing & painting;Digital illustration;Style development;Exhibiting", "Procreate;Photoshop;Traditional media",
   2, 20, 3, 4, 0.60, 0.35, 0.80, "Mumbai;Delhi;Baroda;Online",
   "Graphic Design & Visual Communication;Animation & VFX;Content Creation & New Media"),
  ("Jewellery & Accessory Design", "Design", "craft aesthetic detail luxury creative",
   "Design jewellery — heritage craft meets modern retail.",
   "Art;Chemistry", "B.Des Jewellery (NIFT);Gemology diplomas (GIA/IIGJ)",
   "Design & rendering;Gemology;CAD for jewellery;Craft techniques", "Jewellery CAD;Rhino;Workshop tools",
   3, 15, 2, 3, 0.65, 0.20, 0.20, "Mumbai;Jaipur;Surat;Delhi",
   "Fashion Design;Furniture & Product Design;Retail Management"),
  ("Textile & Craft Design", "Design", "craft heritage textiles creative detail",
   "Design fabrics and revive India's craft traditions for global markets.",
   "Art;Home Science;Chemistry", "B.Des Textile (NID/NIFT);Craft-cluster programmes",
   "Weave & print design;Material innovation;Craft collaboration;Sustainability", "Textile CAD;Looms;Dye labs",
   3, 12, 2, 2, 0.65, 0.20, 0.30, "Ahmedabad;Jaipur;Varanasi;Craft clusters",
   "Fashion Design;Furniture & Product Design;Rural Livelihoods & Development"),
  ("Art Direction & Advertising", "Storytelling", "creative visual campaigns ideas leadership",
   "Lead the visual side of campaigns and brand worlds.",
   "Art;English;Business Studies", "B.Des/BFA;Mass Comm;Portfolio + agency ladder",
   "Campaign ideation;Visual direction;Team collaboration;Pitching", "Adobe suite;Figma;AI image tools",
   4, 25, 3, 4, 0.75, 0.30, 0.60, "Mumbai;Gurugram;Bengaluru",
   "Graphic Design & Visual Communication;Advertising & Brand Management;Content Creation & New Media"),
 ]),

 "communication-marketing": ("Communication, Marketing & Sales", "📣",
  "Move minds and markets — media, marketing, sales and the attention economy.", [
  ("Digital Marketing", "Marketing", "marketing creativity analytics digital communication",
   "Grow brands online — search, social, ads and analytics.",
   "English;Mathematics;Economics", "Any degree + digital certifications;BBA Marketing",
   "SEO/SEM;Social & content strategy;Performance ads;Analytics", "Google Ads;Meta Ads;GA4;SEO tools",
   4, 30, 2, 4, 0.90, 0.35, 0.90, "Bengaluru;Mumbai;Gurugram;Remote",
   "Content Marketing & Copywriting;Social Media & Community;E-commerce Management"),
  ("Journalism", "Media & News", "news writing curiosity courage truth",
   "Report the news — print, broadcast and digital.",
   "English;Polity;History", "B.A. Journalism/Mass Comm;Any degree + journalism PG",
   "Reporting & verification;Interviewing;News writing;Beat expertise", "CMS;Recording gear;Data tools",
   3, 15, 3, 4, 0.65, 0.30, 0.40, "Delhi;Mumbai;State capitals",
   "Broadcasting & Anchoring;Content Creation & New Media;Science Communication"),
  ("Public Relations & Corporate Communications", "Media & News", "communication relationships reputation writing strategy",
   "Manage what the world thinks of organizations.",
   "English;Business Studies", "B.A. Mass Comm;Any degree + PR skills",
   "Media relations;Press releases;Crisis communication;Executive comms", "Media databases;Monitoring tools",
   4, 18, 2, 3, 0.75, 0.25, 0.60, "Mumbai;Delhi;Bengaluru",
   "Journalism;Advertising & Brand Management;Digital Marketing"),
  ("Advertising & Brand Management", "Marketing", "brands creativity strategy psychology campaigns",
   "Build brands people remember — strategy to campaign.",
   "English;Business Studies;Psychology", "BBA/B.A. + MBA Marketing;Mass Comm",
   "Brand strategy;Campaign planning;Consumer insight;Agency management", "Brand trackers;Adobe basics;Analytics",
   6, 30, 3, 4, 0.75, 0.25, 0.50, "Mumbai;Gurugram;Bengaluru",
   "Art Direction & Advertising;Digital Marketing;Market Research & Insights"),
  ("Content Marketing & Copywriting", "Marketing", "writing persuasion creativity brand digital",
   "Write the words that sell — ads, blogs, scripts and campaigns.",
   "English;Any", "Any degree + portfolio;Mass Comm helps",
   "Copywriting;Content strategy;SEO writing;Editing", "CMS;SEO tools;AI writing assistants",
   3, 25, 2, 4, 0.80, 0.45, 0.95, "Remote;All metros",
   "Digital Marketing;Writing & Publishing;Social Media & Community"),
  ("Social Media & Community", "Marketing", "social digital trends communication creativity",
   "Run the social presence and communities brands live or die by.",
   "English;Any", "Any degree + platform mastery",
   "Platform strategy;Content calendars;Community management;Analytics", "Scheduling tools;Canva;Analytics",
   3, 20, 2, 4, 0.85, 0.40, 0.95, "Remote;All metros",
   "Digital Marketing;Content Creation & New Media;Influencer & Creator Management"),
  ("Content Creation & New Media", "Media & News", "creator video audience independence storytelling",
   "Build your own audience — YouTube, podcasts, newsletters.",
   "Any;English", "No degree required — portfolio is the degree",
   "Content production;Audience growth;Monetization;Consistency", "Cameras;Editing apps;Analytics",
   1, 100, 2, 5, 0.80, 0.30, 1.00, "Anywhere",
   "Video Editing & Post-Production;Social Media & Community;Content Marketing & Copywriting"),
  ("Sales & Business Development", "Sales & Growth", "persuasion people resilience targets relationships",
   "Sell — the skill every company pays for and few master.",
   "Any;Business Studies", "Any degree;MBA for enterprise sales",
   "Prospecting;Negotiation;Relationship building;Pipeline management", "CRM (Salesforce);LinkedIn;Email tools",
   4, 40, 2, 3, 0.90, 0.25, 0.60, "All cities",
   "Business Management;Customer Success;Real Estate & Property Management"),
  ("Customer Success", "Sales & Growth", "people service empathy technology retention",
   "Keep customers winning after the sale — SaaS's people profession.",
   "English;Any", "Any degree + product aptitude",
   "Onboarding;Relationship management;Upsell & renewal;Product expertise", "CRM;Support platforms;Analytics",
   5, 20, 2, 3, 0.80, 0.30, 0.90, "Bengaluru;Pune;Hyderabad;Remote",
   "Sales & Business Development;Product Management;Human Resources"),
  ("Market Research & Insights", "Strategy & Insights", "research data psychology curiosity analytical",
   "Find out what people really think and buy — the insight engine of business.",
   "Mathematics;Psychology;Economics", "B.A./B.Sc + MBA/M.Sc;Statistics helps",
   "Survey design;Qualitative research;Statistical analysis;Insight storytelling", "SPSS;Excel;Survey platforms",
   5, 18, 3, 3, 0.75, 0.35, 0.70, "Mumbai;Gurugram;Bengaluru",
   "Business Analytics;Consumer Psychology;Advertising & Brand Management"),
  ("Broadcasting & Anchoring", "Media & News", "voice presence confidence current-affairs performance",
   "Anchor news, radio and live events.",
   "English;Polity;Any", "Mass Comm;Any degree + screen presence",
   "On-camera presence;Voice modulation;Scripting;Live improvisation", "Teleprompters;Studio systems",
   3, 25, 3, 5, 0.60, 0.25, 0.20, "Delhi;Mumbai;Regional channels",
   "Journalism;Radio & Podcasting;Acting & Theatre"),
  ("Radio & Podcasting", "Media & News", "voice audio storytelling conversation creativity",
   "Own the audio wave — RJing and the podcast boom.",
   "English;Any", "Mass Comm;Any degree + demo",
   "Voice craft;Show production;Interviewing;Audience building", "Mics;DAWs;Hosting platforms",
   2, 20, 2, 4, 0.65, 0.30, 0.85, "Mumbai;Delhi;Anywhere",
   "Broadcasting & Anchoring;Content Creation & New Media;Sound Engineering"),
  ("SEO & Growth Marketing", "Sales & Growth", "analytics digital experimentation growth technical",
   "Engineer growth — rankings, funnels and experiments.",
   "Mathematics;English;Computer Science", "Any degree + demonstrated results",
   "SEO;Funnel optimization;A/B testing;Analytics", "GA4;Search Console;SQL basics;Ahrefs",
   5, 30, 3, 4, 0.85, 0.40, 0.95, "Bengaluru;Remote;All metros",
   "Digital Marketing;Business Analytics;Product Management"),
  ("Influencer & Creator Management", "Sales & Growth", "creators partnerships negotiation trends people",
   "Manage creators and brand collaborations — the new talent industry.",
   "English;Business Studies", "Any degree + industry hustle",
   "Talent management;Deal making;Campaign coordination;Brand safety", "CRM;Social analytics;Contracts",
   4, 15, 2, 3, 0.75, 0.25, 0.80, "Mumbai;Bengaluru;Delhi",
   "Social Media & Community;Advertising & Brand Management;Event Management"),
  ("Translation & Interpretation", "Media & News", "languages precision culture service communication",
   "Bridge languages — translation, interpretation and localization.",
   "Languages;English", "B.A. Languages;Translation diplomas;Certification (e.g. JLPT)",
   "Translation accuracy;Interpretation;Localization;Domain terminology", "CAT tools;Subtitling software",
   3, 15, 2, 2, 0.70, 0.50, 0.90, "Delhi;Bengaluru;Remote worldwide",
   "Language Teaching;Diplomacy & International Relations;Content Creation & New Media"),
  ("Media Planning & Buying", "Strategy & Insights", "media numbers strategy negotiation analytics",
   "Decide where advertising money goes — and prove it worked.",
   "Mathematics;Economics;English", "BBA/Mass Comm + agency training",
   "Media strategy;Budget allocation;Negotiation;Campaign measurement", "Planning tools;DSPs;Excel",
   4, 20, 2, 3, 0.75, 0.40, 0.60, "Mumbai;Gurugram;Bengaluru",
   "Advertising & Brand Management;Digital Marketing;Market Research & Insights"),
  ("Consumer Psychology", "Strategy & Insights", "psychology behaviour research marketing curious",
   "Understand why people buy — behavioural science applied to markets.",
   "Psychology;Mathematics;Economics", "B.A. Psychology + M.A./MBA;Behavioural science courses",
   "Behavioural research;Experiment design;Persuasion science;Insight translation", "Survey tools;R/SPSS;Eye-tracking",
   5, 15, 3, 3, 0.70, 0.20, 0.70, "Mumbai;Bengaluru;Gurugram",
   "Market Research & Insights;Organizational Psychology;Advertising & Brand Management"),
  ("Event & Experiential Marketing", "Sales & Growth", "events energy organization creativity people",
   "Create live brand experiences — launches, activations, roadshows.",
   "Business Studies;English", "BBA;Event management diplomas",
   "Event conceptualization;Vendor management;On-ground execution;Sponsorships", "Project tools;AV systems",
   3, 18, 2, 3, 0.75, 0.15, 0.20, "Mumbai;Delhi;Bengaluru",
   "Event Management;Advertising & Brand Management;Influencer & Creator Management"),
 ]),

 "agriculture-environment": ("Agriculture, Food & Environment", "🌾",
  "Feed the country and protect the planet — agri-science, food systems and climate work.", [
  ("Agricultural Science & Agronomy", "Agri Science", "farming science outdoors soil practical",
   "Make farms more productive and sustainable — the science of crops.",
   "Biology;Chemistry;Agriculture", "B.Sc Agriculture;+ M.Sc Agronomy",
   "Crop science;Soil health;Pest management;Farm advisory", "Soil testing;Drones;Field kits",
   3, 12, 3, 2, 0.85, 0.20, 0.10, "Agri universities;All rural India",
   "Precision Agriculture & AgriTech;Horticulture & Floriculture;Agricultural Extension & Advisory"),
  ("Horticulture & Floriculture", "Agri Science", "plants outdoors science aesthetic practical",
   "Grow fruits, vegetables and flowers — high-value farming.",
   "Biology;Agriculture", "B.Sc Horticulture",
   "Orchard & nursery management;Protected cultivation;Post-harvest;Marketing", "Greenhouses;Irrigation systems",
   3, 10, 3, 2, 0.80, 0.15, 0.10, "Maharashtra;Himachal;Karnataka;All states",
   "Agricultural Science & Agronomy;Landscape & Nursery Business;Food Technology"),
  ("Food Technology", "Food Systems", "food science lab innovation quality",
   "Turn harvests into safe, packaged, delicious products.",
   "Chemistry;Biology;Physics", "B.Tech Food Technology;B.Sc Food Science",
   "Food processing;Preservation;Quality & safety systems;Product development", "Lab equipment;Processing lines",
   4, 15, 3, 3, 0.85, 0.30, 0.20, "Pune;Bengaluru;NCR;Food parks",
   "Food Safety & Quality;Dairy & Animal Husbandry;Culinary Arts & Chef Careers"),
  ("Dairy & Animal Husbandry", "Agri Science", "animals farming science practical rural",
   "Run the world's largest dairy system — breeding, nutrition, production.",
   "Biology;Agriculture", "B.Tech Dairy Technology;B.Sc Animal Husbandry;B.V.Sc",
   "Animal nutrition;Breeding;Dairy processing;Farm management", "Milking systems;Cold chain",
   3, 10, 3, 2, 0.80, 0.20, 0.05, "Gujarat;Punjab;Karnataka;Rural India",
   "Veterinary Science;Food Technology;Agri-business & Rural Entrepreneurship"),
  ("Fisheries & Aquaculture", "Agri Science", "aquatic farming science outdoors practical",
   "Farm fish and shrimp — India's blue economy.",
   "Biology;Chemistry", "B.F.Sc (Fisheries Science)",
   "Aquaculture systems;Hatchery management;Water quality;Harvest & marketing", "Ponds & RAS systems;Testing kits",
   3, 8, 3, 2, 0.75, 0.15, 0.05, "Andhra;Kerala;West Bengal;Coasts",
   "Oceanography & Meteorology;Food Technology;Agri-business & Rural Entrepreneurship"),
  ("Forestry & Wildlife Management", "Environment", "forests wildlife outdoors conservation service",
   "Manage forests and wild landscapes — IFS and beyond.",
   "Biology;Geography", "B.Sc Forestry;+ Indian Forest Service exam",
   "Forest management;Wildlife census;Conservation planning;Community forestry", "GIS;Camera traps;Field gear",
   4, 10, 4, 2, 0.70, 0.10, 0.05, "Forest divisions nationwide;Dehradun",
   "Wildlife Conservation;Environmental Science;Civil Services (IAS/IPS/IFS)"),
  ("Wildlife Conservation", "Environment", "wildlife nature research fieldwork mission",
   "Protect species and habitats — research, NGOs and policy.",
   "Biology;Geography", "B.Sc Zoology/Wildlife + M.Sc Wildlife Science (WII)",
   "Field research;Species monitoring;Community engagement;Grant writing", "Camera traps;GIS;Statistical tools",
   3, 10, 4, 3, 0.65, 0.05, 0.10, "Field sites;Dehradun;Bengaluru NGOs",
   "Forestry & Wildlife Management;Environmental Science;Adventure Tourism & Ecotourism"),
  ("Environmental Management & Sustainability", "Environment", "sustainability systems analysis mission corporate",
   "Run sustainability for companies — audits, EIA, circular economy.",
   "Biology;Chemistry;Geography", "B.Sc Environmental Science + M.Sc/MBA Sustainability",
   "Environmental audits;EIA;Sustainability reporting;Waste & water systems", "GIS;LCA tools;Reporting frameworks",
   5, 20, 3, 3, 0.85, 0.15, 0.50, "Mumbai;Bengaluru;Delhi;Industrial belts",
   "Climate & ESG Careers;Environmental Science;Waste Management & Circular Economy"),
  ("Climate & ESG Careers", "Environment", "climate finance policy analysis emerging mission",
   "Work the climate transition — carbon markets, ESG reporting, green finance.",
   "Economics;Environmental Science;Mathematics", "Any degree + ESG/climate specialization;Engineering/Eco background helps",
   "Carbon accounting;ESG frameworks;Climate risk analysis;Reporting", "GHG protocols;Excel;ESG platforms",
   6, 30, 4, 4, 0.90, 0.15, 0.70, "Mumbai;Bengaluru;Delhi;Global remote",
   "Environmental Management & Sustainability;Renewable Energy Engineering;Financial Analysis"),
  ("Precision Agriculture & AgriTech", "Food Systems", "agritech drones data farming innovation",
   "Bring sensors, drones and AI to Indian farms.",
   "Agriculture;Mathematics;Computer Science", "B.Sc Agri + tech skills;B.Tech + agri domain",
   "Farm data analysis;Drone operations;IoT deployment;Farmer advisory", "Drones;IoT sensors;GIS;Python basics",
   5, 20, 4, 3, 0.85, 0.15, 0.40, "Bengaluru;Pune;Hyderabad;Field",
   "Agricultural Science & Agronomy;Data & Artificial Intelligence;Drone Operations & Services"),
  ("Agricultural Extension & Advisory", "Agri Science", "teaching farmers service communication rural",
   "Carry science to the farm gate — the KVK and advisory network.",
   "Agriculture;Biology", "B.Sc Agriculture + extension roles;State agri services",
   "Farmer training;Demonstration plots;Scheme delivery;Local trust", "Mobile advisory;Demo kits",
   3, 8, 3, 2, 0.75, 0.15, 0.05, "Every district (KVKs);Rural India",
   "Agricultural Science & Agronomy;Rural Livelihoods & Development;Agri-business & Rural Entrepreneurship"),
  ("Agri-business & Rural Entrepreneurship", "Food Systems", "entrepreneurship rural farming markets practical",
   "Build businesses in the farm economy — FPOs, inputs, processing, exports.",
   "Agriculture;Business Studies;Economics", "B.Sc Agri + MBA Agribusiness;Any + rural venture",
   "Agri value chains;FPO management;Rural marketing;Finance basics", "Mandi platforms;Excel;Logistics apps",
   0, 50, 3, 3, 0.80, 0.10, 0.20, "Rural India;Agri hubs",
   "Entrepreneurship & Startups;Dairy & Animal Husbandry;Rural Livelihoods & Development"),
  ("Food Safety & Quality", "Food Systems", "quality lab detail rules science",
   "Keep food safe — FSSAI, labs and factory QA.",
   "Chemistry;Biology", "B.Sc Food Science;B.Tech Food Tech + FSSAI exams",
   "Food testing;HACCP & audits;Regulatory compliance;Documentation", "Lab analysis;Audit checklists",
   4, 12, 3, 2, 0.80, 0.30, 0.20, "All food industry hubs",
   "Food Technology;Medical Laboratory Science;Legal Compliance & Governance"),
  ("Soil & Water Conservation", "Environment", "soil water outdoors engineering service",
   "Save the two resources farming cannot exist without.",
   "Agriculture;Geography;Physics", "B.Sc Agri/B.Tech Agricultural Engineering",
   "Watershed planning;Irrigation design;Soil surveys;Community mobilization", "GIS;Survey tools;Irrigation tech",
   3, 8, 3, 2, 0.75, 0.15, 0.05, "Watershed projects nationwide",
   "Agricultural Engineering;Environmental Science;Rural Livelihoods & Development"),
  ("Agricultural Engineering", "Food Systems", "machines farming engineering practical innovation",
   "Engineer the machines and systems of modern farming.",
   "Physics;Mathematics;Agriculture", "B.Tech Agricultural Engineering",
   "Farm machinery;Irrigation systems;Post-harvest engineering;Renewable on-farm energy", "CAD;Farm equipment;Sensors",
   4, 10, 3, 2, 0.75, 0.25, 0.10, "Punjab;Tamil Nadu;Agri-machine hubs",
   "Mechanical Engineering;Precision Agriculture & AgriTech;Soil & Water Conservation"),
  ("Waste Management & Circular Economy", "Environment", "recycling systems sustainability entrepreneurship service",
   "Turn India's waste problem into a resource economy.",
   "Chemistry;Biology;Environmental Science", "B.Sc/B.Tech Environmental;Any + sector entry",
   "Waste systems design;Recycling operations;EPR compliance;Community programmes", "MRF systems;Tracking platforms",
   4, 12, 3, 2, 0.85, 0.25, 0.20, "All cities;ULB projects",
   "Environmental Management & Sustainability;Urban Governance & Administration;Social Entrepreneurship"),
  ("Landscape & Nursery Business", "Agri Science", "plants design outdoors business aesthetic",
   "Design green spaces and grow the plants for them.",
   "Biology;Art;Agriculture", "B.Sc Horticulture;Landscape diplomas",
   "Landscape design;Plant propagation;Project execution;Client service", "CAD basics;Nursery systems",
   3, 8, 2, 2, 0.70, 0.15, 0.10, "All metros;Tourist regions",
   "Horticulture & Floriculture;Interior & Spatial Design;Landscape Architecture"),
  ("Rural Livelihoods & Development", "Food Systems", "rural service community development mission",
   "Build livelihoods in villages — SHGs, NRLM, development programmes.",
   "Social Science;Agriculture;Economics", "Any degree + rural management (IRMA);M.A. Development",
   "Community mobilization;Programme management;Livelihood design;M&E", "MIS systems;Survey apps",
   4, 12, 3, 2, 0.80, 0.05, 0.10, "Rural districts;State missions",
   "Social Work;NGO & Development Management;Agri-business & Rural Entrepreneurship"),
 ]),

 "construction-urban": ("Construction, Architecture & Urban Development", "🏗️",
  "Shape skylines and cities — design, build and manage the built environment.", [
  ("Architecture", "Design & Planning", "design creativity structures aesthetics vision",
   "Design buildings that people live, work and dream in.",
   "Mathematics;Physics;Art", "B.Arch (via NATA/JEE);+ M.Arch",
   "Architectural design;Drawing & modelling;Building codes;Client presentation", "AutoCAD;Revit;SketchUp;Rhino",
   4, 25, 4, 4, 0.75, 0.15, 0.30, "Mumbai;Delhi;Bengaluru;Ahmedabad",
   "Interior & Spatial Design;Urban & Regional Planning;Landscape Architecture"),
  ("Urban & Regional Planning", "Design & Planning", "cities systems planning policy analytical",
   "Plan how cities grow — transport, housing, land use.",
   "Geography;Mathematics;Economics", "B.Plan;B.Arch + M.Plan",
   "Master planning;GIS analysis;Transport planning;Policy drafting", "GIS;AutoCAD;Modelling tools",
   5, 15, 3, 3, 0.80, 0.15, 0.30, "Delhi;State capitals;Smart-city SPVs",
   "Urban Governance & Administration;Architecture;Infrastructure Planning & Development"),
  ("Construction Management", "Construction Delivery", "execution leadership site coordination practical",
   "Deliver projects on time and on budget — the site's commanding officer.",
   "Physics;Mathematics", "B.Tech Civil + construction management;NICMAR",
   "Project scheduling;Contract administration;Site coordination;Cost control", "MS Project;Primavera;ERP",
   6, 25, 3, 3, 0.85, 0.20, 0.10, "All metros;Infrastructure corridors",
   "Civil Engineering;Quantity Surveying & Estimation;Infrastructure Planning & Development"),
  ("Quantity Surveying & Estimation", "Construction Delivery", "numbers detail contracts costs analytical",
   "Measure and price everything a project needs.",
   "Mathematics;Physics", "B.Tech Civil;QS diplomas (RICS pathways)",
   "Quantity take-off;Cost estimation;Tendering;Contract claims", "CostX;Excel;BIM tools",
   4, 15, 3, 2, 0.80, 0.35, 0.30, "All metros;Gulf demand high",
   "Construction Management;Valuation & Property Consulting;Civil Engineering"),
  ("Structural & Infrastructure Planning", "Design & Planning", "structures mathematics safety precision analytical",
   "Design the skeletons of buildings and bridges.",
   "Physics;Mathematics", "B.Tech Civil + M.Tech Structures",
   "Structural analysis;Seismic design;Detailing;Peer review", "STAAD;ETABS;SAFE",
   6, 18, 4, 3, 0.80, 0.25, 0.30, "All metros;Consultancies",
   "Civil Engineering;Architecture;Construction Management"),
  ("Real Estate Development", "Property & Assets", "property business vision finance negotiation",
   "Conceive and deliver real-estate projects — land to launch.",
   "Economics;Business Studies;Mathematics", "BBA/B.Tech + real-estate MBA;RICS",
   "Feasibility analysis;Approvals & liaison;Project finance;Sales strategy", "Excel;Project tools;CRM",
   6, 40, 3, 3, 0.75, 0.15, 0.20, "Mumbai;NCR;Bengaluru;Pune",
   "Real Estate & Property Management;Construction Management;Valuation & Property Consulting"),
  ("Building Services (MEP)", "Construction Delivery", "systems electrical mechanical detail practical",
   "Design a building's lungs and nerves — HVAC, electrical, plumbing, fire.",
   "Physics;Mathematics", "B.Tech Mechanical/Electrical + MEP specialization",
   "HVAC design;Electrical layouts;Plumbing & fire systems;Coordination", "Revit MEP;HAP;Dialux",
   5, 15, 3, 2, 0.80, 0.30, 0.30, "All metros;Gulf demand",
   "Electrical & Electronics Engineering;Mechanical Engineering;Green Building & Sustainable Design"),
  ("Green Building & Sustainable Design", "Design & Planning", "sustainability design innovation energy mission",
   "Make buildings consume less and give back more.",
   "Physics;Environmental Science;Mathematics", "B.Arch/B.Tech + green building certification (IGBC/LEED)",
   "Energy modelling;Green certification;Passive design;Material selection", "Energy modelling tools;LEED/IGBC frameworks",
   5, 15, 4, 3, 0.85, 0.15, 0.50, "Bengaluru;Mumbai;Delhi",
   "Architecture;Environmental Management & Sustainability;Renewable Energy Engineering"),
  ("Landscape Architecture", "Design & Planning", "nature design outdoors creativity planning",
   "Design parks, campuses and public realms.",
   "Art;Biology;Geography", "B.Arch + M.L.Arch;B.Des Landscape",
   "Site analysis;Planting design;Hardscape detailing;Sustainability", "CAD;GIS;SketchUp",
   4, 10, 3, 2, 0.70, 0.10, 0.30, "Metros;Institutional campuses",
   "Architecture;Landscape & Nursery Business;Urban & Regional Planning"),
  ("Surveying & Geomatics", "Construction Delivery", "measurement precision outdoors mapping technical",
   "Map land and guide construction with millimetre precision.",
   "Mathematics;Geography;Physics", "Diploma/B.Tech Geomatics;ITI Surveyor + experience",
   "Land surveying;GPS/GNSS;Drone mapping;CAD drafting", "Total stations;DGPS;Drones;GIS",
   3, 10, 2, 2, 0.80, 0.30, 0.10, "Everywhere projects run",
   "Civil Engineering;Drone Operations & Services;Urban & Regional Planning"),
  ("Heritage Conservation", "Design & Planning", "history craft culture detail restoration",
   "Restore forts, temples and historic cities.",
   "History;Art;Chemistry", "B.Arch + M.Arch Conservation;Archaeology routes",
   "Conservation planning;Historic material craft;Documentation;Advocacy", "Documentation tools;Traditional materials",
   4, 8, 4, 2, 0.60, 0.05, 0.20, "Heritage cities;ASI circles",
   "Architecture;Museum & Heritage Education;Civil Engineering"),
  ("Facilities Management", "Property & Assets", "operations service systems organization practical",
   "Run buildings after they're built — corporate campuses to malls.",
   "Any;Physics", "Any degree + FM certification;Hotel management routes",
   "Building operations;Vendor management;Safety compliance;Tenant service", "CAFM systems;BMS",
   4, 12, 2, 2, 0.80, 0.30, 0.20, "All metros",
   "Operations Management;Building Services (MEP);Hospitality Operations & Hotel Management"),
  ("Valuation & Property Consulting", "Property & Assets", "numbers property analysis markets detail",
   "Value land and buildings for banks, courts and investors.",
   "Mathematics;Economics", "B.Tech Civil/B.Arch + valuation courses;RICS",
   "Valuation methods;Market analysis;Report writing;Regulatory knowledge", "Valuation models;Excel;GIS basics",
   5, 15, 3, 2, 0.75, 0.30, 0.40, "All metros",
   "Real Estate Development;Quantity Surveying & Estimation;Financial Analysis"),
  ("Infrastructure Planning & Development", "Design & Planning", "infrastructure nation systems planning analytical",
   "Plan highways, metros and ports — nation-building at scale.",
   "Mathematics;Geography;Economics", "B.Tech Civil + M.Tech/M.Plan Infrastructure",
   "Project appraisal;Transport modelling;PPP structuring;Environmental clearances", "GIS;Modelling tools;Excel",
   6, 18, 4, 3, 0.85, 0.15, 0.30, "Delhi;Mumbai;Project corridors",
   "Urban & Regional Planning;Construction Management;Public Policy & Governance"),
  ("Site Supervision & Safety (EHS)", "Construction Delivery", "safety vigilance site discipline practical",
   "Keep construction sites productive and everyone alive.",
   "Physics;Chemistry", "Diploma Civil + safety courses (NEBOSH/IOSH)",
   "Safety audits;Toolbox training;Incident investigation;Compliance", "Safety systems;Checklists;PPE tech",
   4, 10, 2, 2, 0.85, 0.25, 0.05, "Every project site",
   "Construction Management;Manufacturing & Quality Engineering;Firefighting & Emergency Response"),
  ("BIM & Construction Technology", "Construction Delivery", "digital modelling construction technology detail",
   "Digitize construction — 3D building models the whole industry now runs on.",
   "Mathematics;Computer Science;Physics", "B.Tech Civil/B.Arch + BIM certification",
   "BIM modelling;Clash detection;4D/5D simulation;Digital workflows", "Revit;Navisworks;BIM 360",
   5, 18, 3, 2, 0.85, 0.30, 0.60, "All metros;Global remote BIM services",
   "Structural & Infrastructure Planning;Architecture;Software Engineering"),
  ("Contract & Claims Management", "Property & Assets", "contracts negotiation law detail analytical",
   "Manage the legal-commercial spine of big projects.",
   "English;Mathematics;Polity", "B.Tech Civil + contract management;LLB helps",
   "FIDIC contracts;Claims preparation;Arbitration support;Risk allocation", "Contract systems;Excel",
   6, 15, 3, 2, 0.80, 0.25, 0.40, "Metros;International projects",
   "Construction Management;Corporate Law;Quantity Surveying & Estimation"),
 ]),
}
