"""Catalog part 1 — industries 1-6 (see package docstring for the tuple format)."""

INDUSTRIES_1_6 = {
 "technology-computing": ("Technology & Computing", "💻",
  "Build the digital world — software, data, intelligent systems and the infrastructure behind them.", [
  ("Software Engineering", "Software & Applications", "programming logic problem-solving analytical software",
   "Design, build and maintain the software behind apps, websites and digital services.",
   "Mathematics;Computer Science;Physics", "B.Tech/B.E. Computer Science;BCA;B.Sc Computer Science",
   "Programming;Data structures & algorithms;System design;Debugging", "Python;Java;JavaScript;Git;SQL",
   5, 60, 3, 4, 0.95, 0.30, 0.95, "Bengaluru;Hyderabad;Pune;Gurugram;Chennai",
   "Data & Artificial Intelligence;Cybersecurity;Product Management"),
  ("Data & Artificial Intelligence", "Data & AI", "data analytical mathematics curious research programming",
   "Turn data into decisions and build AI systems that learn from it.",
   "Mathematics;Computer Science;Statistics", "B.Tech CSE/AI;B.Sc Statistics/Data Science;B.Sc Mathematics",
   "Statistics;Machine learning;Programming;Data storytelling", "Python;SQL;TensorFlow;Pandas",
   6, 70, 4, 4, 0.95, 0.25, 0.90, "Bengaluru;Hyderabad;Gurugram;Pune",
   "Software Engineering;Data & Analytics Research;Business Analytics"),
  ("Cybersecurity", "Security & Infrastructure", "security analytical detail vigilance problem-solving",
   "Protect systems, networks and people from digital attacks.",
   "Computer Science;Mathematics", "B.Tech CSE/Cybersecurity;BCA + certifications",
   "Network security;Ethical hacking;Incident response;Risk assessment", "Linux;Wireshark;Kali;SIEM tools",
   5, 55, 3, 3, 0.90, 0.20, 0.80, "Bengaluru;Pune;Hyderabad;Mumbai",
   "Software Engineering;Cloud & Infrastructure;Defence Cyber Operations"),
  ("Cloud & Infrastructure", "Security & Infrastructure", "systems analytical automation infrastructure",
   "Run the cloud platforms and servers that keep the internet's services alive.",
   "Computer Science;Mathematics", "B.Tech CSE/IT;BCA + cloud certifications",
   "Cloud architecture;Networking;Automation;Monitoring", "AWS;Azure;Linux;Kubernetes;Terraform",
   5, 55, 3, 3, 0.90, 0.35, 0.90, "Bengaluru;Hyderabad;Pune;Chennai",
   "DevOps & Automation;Cybersecurity;Software Engineering"),
  ("DevOps & Automation", "Security & Infrastructure", "automation systems collaboration problem-solving",
   "Automate how software is built, tested and shipped so teams release faster and safer.",
   "Computer Science;Mathematics", "B.Tech CSE/IT;BCA",
   "CI/CD pipelines;Scripting;Containerization;Reliability engineering", "Docker;Kubernetes;Jenkins;Git;Linux",
   5, 50, 3, 3, 0.85, 0.35, 0.90, "Bengaluru;Pune;Hyderabad;Noida",
   "Cloud & Infrastructure;Software Engineering;Quality Assurance & Testing"),
  ("Product Management", "Product & Design", "leadership communication strategy empathy analytical",
   "Decide what a product should do and lead teams to build it.",
   "Mathematics;Economics;English", "Any bachelor's degree;B.Tech + MBA (common)",
   "Product strategy;User research;Prioritization;Stakeholder communication", "Jira;Figma;Analytics tools;SQL basics",
   8, 60, 3, 4, 0.80, 0.15, 0.80, "Bengaluru;Gurugram;Mumbai;Hyderabad",
   "UX & Interaction Design;Software Engineering;Business Management"),
  ("UX & Interaction Design", "Product & Design", "creative empathy design people detail",
   "Design apps and websites that feel effortless and human.",
   "Art/Design;Psychology;Computer Science", "B.Des Interaction/UX;BFA;Any degree + portfolio",
   "User research;Wireframing;Prototyping;Visual design", "Figma;Adobe XD;Miro",
   4, 30, 2, 3, 0.75, 0.30, 0.85, "Bengaluru;Pune;Mumbai;Gurugram",
   "Graphic Design & Visual Communication;Product Management;Web Development"),
  ("Web Development", "Software & Applications", "programming creative detail web building",
   "Build the websites and web apps people use every day.",
   "Computer Science;Mathematics", "B.Tech/BCA;Any degree + portfolio;Self-taught + bootcamp",
   "HTML/CSS/JavaScript;Frontend frameworks;APIs;Responsive design", "JavaScript;React;Node.js;Git",
   3, 35, 2, 4, 0.85, 0.40, 0.95, "Bengaluru;Pune;Ahmedabad;Jaipur;Remote",
   "Software Engineering;Mobile App Development;UX & Interaction Design"),
  ("Mobile App Development", "Software & Applications", "programming creative building apps detail",
   "Create the mobile apps on billions of phones.",
   "Computer Science;Mathematics", "B.Tech/BCA;Any degree + portfolio",
   "Mobile UI;App architecture;APIs;Publishing & analytics", "Kotlin;Swift;Flutter;Firebase",
   4, 35, 3, 3, 0.80, 0.35, 0.90, "Bengaluru;Hyderabad;Pune;Noida",
   "Web Development;Software Engineering;Game Development"),
  ("Game Development", "Software & Applications", "creative programming storytelling design passion",
   "Design and program games that entertain millions.",
   "Computer Science;Mathematics;Art", "B.Tech CSE;B.Sc Game Design;Any degree + portfolio",
   "Game design;3D graphics programming;Physics simulation;Level design", "Unity;Unreal Engine;C#;C++;Blender",
   4, 25, 3, 4, 0.65, 0.25, 0.75, "Bengaluru;Pune;Hyderabad;Mumbai",
   "Animation & VFX;Software Engineering;AR/VR & Immersive Technology"),
  ("Quality Assurance & Testing", "Software & Applications", "detail analytical patience systematic",
   "Make sure software actually works before the world uses it.",
   "Computer Science;Mathematics", "B.Tech/BCA;B.Sc + testing certifications",
   "Test design;Automation scripting;Bug reporting;Regression analysis", "Selenium;Postman;JIRA;Python",
   4, 30, 2, 3, 0.75, 0.55, 0.85, "Pune;Bengaluru;Chennai;Noida",
   "Software Engineering;DevOps & Automation"),
  ("Data & Database Engineering", "Data & AI", "data systems detail analytical pipelines",
   "Build the pipelines and databases that move and store the world's data.",
   "Computer Science;Mathematics", "B.Tech CSE/IT;BCA;B.Sc CS",
   "Data modelling;ETL pipelines;SQL optimization;Big data systems", "SQL;Spark;Airflow;Snowflake;Python",
   5, 55, 3, 3, 0.90, 0.35, 0.90, "Bengaluru;Hyderabad;Pune;Gurugram",
   "Data & Artificial Intelligence;Cloud & Infrastructure;Software Engineering"),
  ("IT Support & Administration", "Security & Infrastructure", "helpful systematic patience troubleshooting people",
   "Keep an organization's computers, accounts and networks running for everyone.",
   "Computer Science;Mathematics", "BCA;B.Sc IT;Diploma + certifications",
   "Troubleshooting;Networking basics;System administration;User support", "Windows Server;Active Directory;Linux;Helpdesk tools",
   3, 18, 1, 2, 0.70, 0.50, 0.60, "All major cities;Tier-2 cities",
   "Cloud & Infrastructure;Networking & Telecom;Cybersecurity"),
  ("Networking & Telecom", "Security & Infrastructure", "systems detail infrastructure analytical",
   "Design and run the networks that connect everything — from offices to 5G.",
   "Physics;Mathematics;Computer Science", "B.Tech ECE/IT;BCA + network certifications",
   "Network design;Routing & switching;Telecom protocols;Diagnostics", "Cisco;5G stacks;Firewalls;Fiber systems",
   4, 25, 2, 3, 0.70, 0.40, 0.50, "Bengaluru;Gurugram;Mumbai;Chennai",
   "Cloud & Infrastructure;IT Support & Administration;Electronics & Communication Engineering"),
  ("Robotics & Automation", "Emerging Tech", "robotics building curious mathematics engineering",
   "Build robots and automated machines that sense, think and act.",
   "Physics;Mathematics;Computer Science", "B.Tech Mechatronics/Robotics;B.Tech ECE/Mechanical",
   "Robot kinematics;Embedded programming;Control systems;CAD", "ROS;Arduino;Raspberry Pi;C++;Python",
   5, 30, 4, 3, 0.75, 0.15, 0.40, "Bengaluru;Pune;Chennai;Hyderabad",
   "Mechatronics Engineering;Embedded Systems & IoT;Data & Artificial Intelligence"),
  ("Embedded Systems & IoT", "Emerging Tech", "electronics programming detail building curious",
   "Program the tiny computers inside cars, appliances and smart devices.",
   "Physics;Mathematics;Computer Science", "B.Tech ECE/EEE;B.Tech CSE",
   "Microcontroller programming;Circuit basics;RTOS;Sensor integration", "C;C++;Arduino;ARM;MQTT",
   5, 30, 4, 3, 0.75, 0.20, 0.50, "Bengaluru;Pune;Hyderabad;Noida",
   "Robotics & Automation;Electronics & Communication Engineering;Software Engineering"),
  ("AR/VR & Immersive Technology", "Emerging Tech", "creative programming design curious emerging",
   "Build augmented and virtual reality experiences for games, training and design.",
   "Computer Science;Mathematics;Art", "B.Tech CSE;B.Des;Any degree + portfolio",
   "3D development;Interaction design;Spatial computing;Optimization", "Unity;Unreal;WebXR;Blender",
   4, 20, 4, 3, 0.70, 0.20, 0.70, "Bengaluru;Hyderabad;Mumbai;Pune",
   "Game Development;Animation & VFX;UX & Interaction Design"),
  ("Blockchain & Web3", "Emerging Tech", "programming analytical curious emerging finance",
   "Build decentralized apps, smart contracts and digital-asset systems.",
   "Computer Science;Mathematics;Economics", "B.Tech CSE;BCA + specialization",
   "Smart contracts;Cryptography basics;Distributed systems;Token economics", "Solidity;Ethereum;Rust;Web3.js",
   5, 40, 4, 4, 0.55, 0.20, 0.90, "Bengaluru;Remote;Mumbai;Gurugram",
   "Software Engineering;FinTech;Cybersecurity"),
  ("Technical Writing", "Product & Design", "writing communication detail teaching clarity",
   "Explain complex technology so clearly that anyone can use it.",
   "English;Computer Science", "Any bachelor's degree;B.A. English/Communication + tech skills",
   "Clear writing;Information architecture;API documentation;Editing", "Markdown;Git;Docs-as-code;Screen capture tools",
   4, 25, 2, 2, 0.65, 0.45, 0.95, "Bengaluru;Pune;Hyderabad;Remote",
   "Software Engineering;Content Marketing & Copywriting;Curriculum & Instructional Design"),
 ]),

 "business-finance": ("Business, Finance & Economics", "📈",
  "Run, fund and grow organizations — from startups to global markets.", [
  ("Chartered Accountancy", "Accounting & Audit", "numbers detail discipline analytical finance",
   "Become India's trusted expert on accounts, audit and tax.",
   "Accountancy;Mathematics;Economics", "CA (ICAI) after Class 12/B.Com;B.Com + CA",
   "Accounting standards;Auditing;Taxation;Financial reporting", "Tally;Excel;GST portals;Audit tools",
   7, 40, 4, 5, 0.85, 0.35, 0.40, "Mumbai;Delhi;Bengaluru;Ahmedabad;Kolkata",
   "Auditing & Taxation;Financial Analysis;Investment Banking"),
  ("Financial Analysis", "Finance & Investment", "numbers analytical detail markets research",
   "Analyze companies and investments to guide where money goes.",
   "Mathematics;Economics;Accountancy", "B.Com;BBA Finance;B.Sc Economics + CFA",
   "Financial modelling;Valuation;Excel analysis;Report writing", "Excel;PowerPoint;Bloomberg;SQL basics",
   6, 35, 3, 4, 0.85, 0.40, 0.60, "Mumbai;Gurugram;Bengaluru;Pune",
   "Investment Banking;Chartered Accountancy;Business Analytics"),
  ("Investment Banking", "Finance & Investment", "numbers ambition analytical stamina markets",
   "Help companies raise money, merge and go public — high stakes, high pace.",
   "Mathematics;Economics;Accountancy", "BBA/B.Com + MBA Finance;Economics degree + CFA",
   "Valuation;Deal structuring;Pitch books;Negotiation", "Excel;PowerPoint;Bloomberg;Data rooms",
   12, 80, 5, 5, 0.70, 0.25, 0.30, "Mumbai;Gurugram;Bengaluru",
   "Financial Analysis;Management Consulting;Stock Markets & Trading"),
  ("Banking & Financial Services", "Finance & Investment", "numbers people service detail trust",
   "Run the banks and NBFCs that power saving, lending and payments.",
   "Mathematics;Economics;Accountancy", "B.Com;BBA;Any degree + banking exams (IBPS/SBI)",
   "Credit assessment;Customer advisory;Compliance;Branch operations", "Core banking systems;Excel;CRM",
   4, 18, 2, 4, 0.75, 0.45, 0.30, "All major cities;Tier-2 and Tier-3 cities",
   "Insurance & Actuarial Science;Financial Analysis;FinTech"),
  ("Insurance & Actuarial Science", "Finance & Investment", "mathematics statistics analytical risk detail",
   "Use mathematics to price risk — from health policies to catastrophes.",
   "Mathematics;Statistics;Economics", "B.Sc Statistics/Mathematics + Actuarial exams (IAI);B.Com",
   "Probability & statistics;Risk modelling;Insurance products;Data analysis", "Excel;R;Python;Actuarial software",
   8, 50, 4, 3, 0.75, 0.30, 0.60, "Mumbai;Gurugram;Bengaluru;Pune",
   "Financial Analysis;Data & Artificial Intelligence;Banking & Financial Services"),
  ("Stock Markets & Trading", "Finance & Investment", "markets numbers risk decisiveness analytical",
   "Trade and analyze markets — equities, derivatives and beyond.",
   "Mathematics;Economics", "B.Com/BBA;Any degree + NISM certifications",
   "Market analysis;Risk management;Technical & fundamental analysis;Discipline", "Trading terminals;Excel;Python;Screeners",
   4, 60, 4, 5, 0.65, 0.45, 0.80, "Mumbai;Ahmedabad;Delhi;Bengaluru",
   "Financial Analysis;Investment Banking;FinTech"),
  ("Economics & Policy Analysis", "Economics & Policy", "economics research analytical writing curious",
   "Study how economies work and advise governments and firms on policy.",
   "Economics;Mathematics;Statistics", "B.A./B.Sc Economics;+ M.A. Economics (recommended)",
   "Economic modelling;Econometrics;Policy writing;Data analysis", "Stata;R;Excel;Python",
   6, 35, 4, 3, 0.70, 0.20, 0.60, "Delhi;Mumbai;Bengaluru;Hyderabad",
   "Public Policy & Governance;Financial Analysis;Social Research & Sociology"),
  ("Business Management", "Management & Strategy", "leadership organization people communication execution",
   "Run teams and operations that make organizations deliver.",
   "Business Studies;Economics;Mathematics", "BBA;B.Com;Any degree + MBA",
   "Planning & execution;Team leadership;Budgeting;Communication", "Excel;PowerPoint;ERP systems",
   5, 30, 2, 4, 0.80, 0.25, 0.50, "Mumbai;Delhi;Bengaluru;All metros",
   "Operations Management;Human Resources;Management Consulting"),
  ("Management Consulting", "Management & Strategy", "analytical problem-solving communication ambition strategy",
   "Solve companies' hardest problems as an outside expert.",
   "Mathematics;Economics;Business Studies", "Any strong bachelor's + MBA (typical);Engineering + MBA",
   "Structured problem solving;Business analysis;Storylining;Client management", "PowerPoint;Excel;Survey tools",
   12, 90, 5, 5, 0.75, 0.20, 0.60, "Gurugram;Mumbai;Bengaluru",
   "Business Management;Financial Analysis;Product Management"),
  ("Entrepreneurship & Startups", "Management & Strategy", "risk creativity leadership resilience vision",
   "Start and grow your own venture — build something from nothing.",
   "Business Studies;Economics;Any", "Any degree;BBA;Learning by building (accelerators/incubators)",
   "Opportunity spotting;Sales;Fundraising;Product thinking", "No-code tools;Spreadsheets;Analytics",
   0, 100, 4, 5, 0.75, 0.10, 0.70, "Bengaluru;Mumbai;Delhi;Anywhere",
   "Product Management;Digital Marketing;Business Management"),
  ("Human Resources", "People & Operations", "people empathy communication fairness organization",
   "Hire, grow and support the people who make organizations work.",
   "Business Studies;Psychology;English", "BBA HR;B.A. Psychology;Any degree + MBA HR",
   "Recruitment;People development;Conflict resolution;HR analytics", "HRMS;LinkedIn;Excel",
   4, 20, 2, 3, 0.75, 0.35, 0.60, "All major cities",
   "Organizational Psychology;Business Management;Corporate Training & L&D"),
  ("Operations Management", "People & Operations", "organization systematic efficiency problem-solving execution",
   "Make products and services flow — factories, warehouses, service centres.",
   "Mathematics;Business Studies", "BBA;B.Tech + MBA Ops;B.Com",
   "Process design;Capacity planning;Quality management;Vendor management", "ERP;Excel;Lean/Six Sigma tools",
   5, 22, 3, 3, 0.80, 0.40, 0.30, "Mumbai;Chennai;Pune;NCR",
   "Supply Chain Management;Business Management;Manufacturing & Quality Engineering"),
  ("Business Analytics", "Data & Strategy", "data analytical business curiosity numbers",
   "Turn business data into dashboards and decisions.",
   "Mathematics;Statistics;Economics", "BBA Analytics;B.Sc Statistics;B.Com + analytics certification",
   "SQL & dashboards;Statistical analysis;Business storytelling;Experimentation", "SQL;Power BI;Tableau;Python;Excel",
   6, 40, 3, 4, 0.90, 0.35, 0.85, "Bengaluru;Gurugram;Mumbai;Hyderabad",
   "Data & Artificial Intelligence;Financial Analysis;Market Research & Insights"),
  ("FinTech", "Data & Strategy", "finance technology innovation analytical product",
   "Reinvent money — payments, lending and investing built as software.",
   "Mathematics;Computer Science;Economics", "B.Tech + finance;BBA/B.Com + tech skills",
   "Payments systems;Product analytics;Risk & compliance basics;APIs", "APIs;SQL;Excel;Python",
   7, 50, 3, 4, 0.85, 0.25, 0.80, "Bengaluru;Mumbai;Gurugram;Pune",
   "Software Engineering;Banking & Financial Services;Product Management"),
  ("E-commerce Management", "Data & Strategy", "business digital organization marketing analytical",
   "Run online stores and marketplaces — catalogue to doorstep.",
   "Business Studies;Mathematics;Economics", "BBA;B.Com;Any degree + digital skills",
   "Marketplace operations;Pricing & promotions;Category management;Analytics", "Seller platforms;Excel;Analytics dashboards",
   4, 25, 2, 3, 0.80, 0.35, 0.70, "Bengaluru;Gurugram;Mumbai;Hyderabad",
   "Digital Marketing;Supply Chain Management;Operations Management"),
  ("Auditing & Taxation", "Accounting & Audit", "numbers detail rules integrity analytical",
   "Keep organizations honest and tax-compliant.",
   "Accountancy;Mathematics;Economics", "B.Com;CA/CMA;LLB (tax law)",
   "Audit procedures;GST & income tax;Documentation;Analysis", "Tally;Excel;Tax software",
   4, 25, 3, 4, 0.80, 0.45, 0.40, "All major cities;Tier-2 cities",
   "Chartered Accountancy;Taxation & Corporate Law;Financial Analysis"),
  ("Real Estate & Property Management", "People & Operations", "negotiation people markets local sales",
   "Develop, sell and manage property — one of India's biggest sectors.",
   "Business Studies;Economics", "BBA;Any degree + RERA knowledge;B.Plan",
   "Negotiation;Market valuation;Client management;Documentation", "CRM;Excel;Listing platforms",
   3, 30, 2, 3, 0.70, 0.20, 0.30, "Mumbai;NCR;Bengaluru;Pune;Hyderabad",
   "Real Estate Development;Sales & Business Development;Valuation & Property Consulting"),
  ("Retail Management", "People & Operations", "people service organization sales execution",
   "Run stores and retail chains that serve millions daily.",
   "Business Studies;Economics", "BBA Retail;B.Com;Any degree",
   "Store operations;Merchandising;Team management;Customer experience", "POS systems;Excel;Inventory software",
   3, 15, 2, 3, 0.70, 0.40, 0.20, "All major cities;Tier-2 cities",
   "E-commerce Management;Operations Management;Sales & Business Development"),
 ]),

 "healthcare-medicine": ("Healthcare & Medicine", "🩺",
  "Care for human health — from the clinic and lab to public health systems.", [
  ("Medicine (Doctor)", "Clinical Care", "care science dedication people resilience",
   "Diagnose and treat patients as a physician — medicine's core path.",
   "Biology;Chemistry;Physics", "MBBS (via NEET);+ MD/MS specialization",
   "Clinical diagnosis;Patient care;Medical procedures;Communication", "Diagnostic equipment;EMR systems",
   8, 80, 5, 5, 0.95, 0.05, 0.20, "All cities;Government & private hospitals",
   "Nursing;Epidemiology & Medical Research;Public Health"),
  ("Nursing", "Clinical Care", "care empathy stamina people service",
   "Be the backbone of patient care in hospitals and communities.",
   "Biology;Chemistry", "B.Sc Nursing;GNM Diploma",
   "Patient care;Clinical procedures;Medication management;Empathy", "Medical devices;EMR systems",
   3, 12, 3, 3, 0.90, 0.10, 0.20, "All cities;Strong international demand",
   "Medicine (Doctor);Paramedical & Emergency Care;Hospital Administration"),
  ("Dentistry", "Clinical Care", "precision care detail hands-on science",
   "Care for teeth and oral health — clinical skill with craftsmanship.",
   "Biology;Chemistry;Physics", "BDS (via NEET);+ MDS specialization",
   "Dental procedures;Diagnosis;Patient management;Precision handwork", "Dental equipment;Imaging",
   5, 30, 4, 4, 0.70, 0.10, 0.10, "All major cities;Own practice anywhere",
   "Medicine (Doctor);Hospital Administration"),
  ("Pharmacy", "Allied Health", "chemistry detail science service care",
   "Be the medicines expert — from the pharmacy counter to drug manufacturing.",
   "Chemistry;Biology;Mathematics", "B.Pharm;D.Pharm;+ M.Pharm",
   "Pharmacology;Dispensing & counselling;Drug safety;Quality control", "Pharmacy software;Lab equipment",
   3, 15, 3, 3, 0.80, 0.30, 0.30, "Hyderabad;Ahmedabad;Mumbai;All cities",
   "Pharmaceutical Research;Medical Laboratory Science;Hospital Administration"),
  ("Physiotherapy", "Allied Health", "care hands-on movement patience people",
   "Restore movement and reduce pain through guided physical treatment.",
   "Biology;Physics", "BPT;+ MPT specialization",
   "Movement assessment;Rehabilitation planning;Manual therapy;Patient motivation", "Therapy equipment;Exercise tools",
   3, 20, 3, 3, 0.80, 0.10, 0.30, "All major cities;Sports academies",
   "Sports Physiotherapy & Rehabilitation;Occupational Therapy;Fitness Training"),
  ("Medical Laboratory Science", "Allied Health", "science detail precision analytical lab",
   "Run the lab tests behind almost every diagnosis.",
   "Biology;Chemistry", "B.Sc MLT;DMLT",
   "Sample analysis;Lab instrumentation;Quality assurance;Reporting", "Analyzers;Microscopes;LIS systems",
   3, 12, 2, 2, 0.85, 0.40, 0.20, "All cities;Diagnostics chains",
   "Microbiology & Immunology;Pharmacy;Epidemiology & Medical Research"),
  ("Radiology & Medical Imaging", "Allied Health", "technology precision science detail imaging",
   "Operate the scanners — X-ray, CT, MRI — that let doctors see inside the body.",
   "Physics;Biology;Chemistry", "B.Sc Radiography/Imaging Technology",
   "Imaging techniques;Patient positioning;Radiation safety;Equipment operation", "X-ray;CT;MRI;PACS",
   4, 15, 3, 2, 0.85, 0.35, 0.20, "All major cities;Hospitals & diagnostics",
   "Medical Laboratory Science;Medicine (Doctor);Biomedical Engineering"),
  ("Public Health", "Health Systems", "community research policy service analytical",
   "Improve health at population scale — prevention, policy and programmes.",
   "Biology;Social Science;Statistics", "MPH after any health/science degree;B.Sc Public Health",
   "Epidemiology;Programme management;Health data analysis;Community engagement", "Excel;R;Survey tools;GIS",
   5, 25, 3, 3, 0.80, 0.15, 0.50, "Delhi;State capitals;NGO hubs",
   "Community Health Work;Epidemiology & Medical Research;Public Policy & Governance"),
  ("Nutrition & Dietetics", "Wellness & Prevention", "health food science people coaching",
   "Turn food science into personalized health guidance.",
   "Biology;Chemistry;Home Science", "B.Sc Nutrition & Dietetics;+ M.Sc/RD",
   "Diet planning;Clinical nutrition;Counselling;Health assessment", "Diet software;Body composition tools",
   3, 15, 2, 3, 0.75, 0.20, 0.60, "All major cities;Online practice",
   "Sports Nutrition;Fitness Training;Wellness & Spa Management"),
  ("Veterinary Science", "Clinical Care", "animals care science hands-on outdoors",
   "Be a doctor for animals — pets, livestock and wildlife.",
   "Biology;Chemistry;Physics", "B.V.Sc & AH (via NEET)",
   "Animal diagnosis & treatment;Surgery;Preventive care;Client communication", "Veterinary equipment;Diagnostics",
   4, 20, 4, 3, 0.75, 0.05, 0.10, "All states;Rural demand high",
   "Dairy & Animal Husbandry;Wildlife Conservation;Medicine (Doctor)"),
  ("Ayurveda & Integrative Medicine", "Wellness & Prevention", "traditional health care holistic science",
   "Practice India's traditional medicine systems with modern rigour.",
   "Biology;Chemistry;Sanskrit", "BAMS (via NEET);BHMS;BUMS",
   "Ayurvedic diagnosis;Herbal pharmacology;Panchakarma;Patient care", "Traditional & modern diagnostics",
   3, 18, 3, 3, 0.70, 0.05, 0.30, "Kerala;All cities;Wellness resorts",
   "Yoga & Mindfulness Instruction;Nutrition & Dietetics;Medicine (Doctor)"),
  ("Optometry", "Allied Health", "precision care science detail people",
   "Test vision and fit the lenses that help people see clearly.",
   "Biology;Physics", "B.Optom",
   "Vision testing;Lens prescription;Eye health screening;Patient advice", "Optical instruments;Refraction tools",
   3, 12, 2, 2, 0.75, 0.25, 0.20, "All major cities;Eyewear chains",
   "Medicine (Doctor);Retail Management"),
  ("Occupational Therapy", "Allied Health", "care patience creativity people rehabilitation",
   "Help people relearn daily life skills after injury or with disability.",
   "Biology;Psychology", "BOT;+ MOT",
   "Functional assessment;Therapy design;Assistive technology;Family coaching", "Therapy tools;Adaptive equipment",
   3, 12, 3, 2, 0.75, 0.05, 0.30, "Metro hospitals;Rehab centres",
   "Physiotherapy;Special Education;Speech & Audiology"),
  ("Speech & Audiology", "Allied Health", "communication care science patience detail",
   "Diagnose and treat speech, language and hearing difficulties.",
   "Biology;Physics;Psychology", "BASLP",
   "Speech assessment;Hearing testing;Therapy delivery;Device fitting", "Audiometers;Therapy software",
   4, 12, 3, 2, 0.75, 0.10, 0.40, "Metro cities;Hospitals & clinics",
   "Occupational Therapy;Special Education;Medicine (Doctor)"),
  ("Mental Health & Psychiatry", "Clinical Care", "empathy science listening care resilience",
   "Treat mental illness as a medical specialist — India needs thousands more.",
   "Biology;Psychology;Chemistry", "MBBS + MD Psychiatry;Clinical Psychology (M.Phil) route",
   "Psychiatric assessment;Treatment planning;Therapy;Crisis management", "Assessment scales;EMR",
   8, 60, 5, 4, 0.90, 0.05, 0.50, "Metro cities;Telepsychiatry",
   "Clinical Psychology;Counselling Psychology;Medicine (Doctor)"),
  ("Hospital Administration", "Health Systems", "organization leadership systems service healthcare",
   "Run hospitals — the operations behind every bed and OT.",
   "Biology;Business Studies;Mathematics", "BBA/B.Sc + MHA;MBBS + MHA",
   "Healthcare operations;Quality & accreditation;Staff coordination;Budgeting", "HIS systems;Excel",
   5, 20, 3, 3, 0.80, 0.20, 0.30, "All major cities;Hospital chains",
   "Public Health;Operations Management;Nursing"),
  ("Paramedical & Emergency Care", "Clinical Care", "quick-thinking care stamina courage service",
   "Be first on scene — emergency medical technicians and OT/ICU technologists.",
   "Biology;Chemistry", "B.Sc Emergency & Trauma Care;Paramedical diplomas",
   "Emergency response;Life support;Equipment operation;Calm under pressure", "Ambulance equipment;Monitors",
   3, 10, 3, 2, 0.85, 0.10, 0.10, "All cities;Ambulance networks",
   "Nursing;Firefighting & Emergency Response;Medicine (Doctor)"),
  ("Epidemiology & Medical Research", "Health Systems", "research science analytical curious data",
   "Study diseases and treatments — the evidence engine of medicine.",
   "Biology;Statistics;Chemistry", "B.Sc Life Sciences + M.Sc/PhD;MBBS + research",
   "Study design;Biostatistics;Clinical trials;Scientific writing", "R;SPSS;Lab equipment;Registries",
   5, 30, 4, 3, 0.80, 0.15, 0.60, "Delhi;Bengaluru;Hyderabad;Pune",
   "Public Health;Biotechnology & Genetics;Data & Artificial Intelligence"),
 ]),

 "engineering-manufacturing": ("Engineering & Manufacturing", "⚙️",
  "Design and build the physical world — machines, structures, energy and production lines.", [
  ("Mechanical Engineering", "Core Engineering", "machines mathematics building analytical hands-on",
   "Design machines and mechanical systems — engineering's broadest foundation.",
   "Physics;Mathematics;Chemistry", "B.Tech/B.E. Mechanical",
   "CAD & design;Thermodynamics;Manufacturing processes;Problem solving", "AutoCAD;SolidWorks;ANSYS;CNC",
   4, 25, 3, 4, 0.75, 0.35, 0.20, "Pune;Chennai;Bengaluru;Coimbatore",
   "Automotive Engineering;Industrial & Production Engineering;Mechatronics Engineering"),
  ("Electrical & Electronics Engineering", "Core Engineering", "electricity mathematics analytical systems detail",
   "Power, machines and electronics — from grids to chips.",
   "Physics;Mathematics", "B.Tech/B.E. EE/EEE",
   "Circuit design;Power systems;Control systems;Testing", "MATLAB;PLC;Embedded tools;CAD",
   4, 25, 3, 4, 0.80, 0.30, 0.25, "Bengaluru;Chennai;Hyderabad;Pune",
   "Electronics & Communication Engineering;Renewable Energy Engineering;Embedded Systems & IoT"),
  ("Electronics & Communication Engineering", "Core Engineering", "electronics mathematics communication analytical detail",
   "Design chips and communication systems — the hardware behind the digital age.",
   "Physics;Mathematics", "B.Tech/B.E. ECE",
   "Circuit & PCB design;Signal processing;Communication systems;Embedded basics", "Verilog;MATLAB;PCB tools;Oscilloscopes",
   5, 30, 3, 4, 0.80, 0.30, 0.35, "Bengaluru;Hyderabad;Chennai;Noida",
   "Embedded Systems & IoT;Networking & Telecom;Semiconductor & VLSI"),
  ("Civil Engineering", "Core Engineering", "structures mathematics outdoors planning practical",
   "Design roads, bridges and buildings — infrastructure that lasts generations.",
   "Physics;Mathematics;Chemistry", "B.Tech/B.E. Civil",
   "Structural analysis;Surveying;Construction methods;Project management", "AutoCAD;STAAD Pro;Total station;BIM",
   4, 20, 3, 3, 0.80, 0.20, 0.10, "All states;Infrastructure corridors",
   "Construction Management;Structural & Infrastructure Planning;Architecture"),
  ("Chemical Engineering", "Core Engineering", "chemistry mathematics processes analytical plant",
   "Turn raw materials into fuels, medicines and materials at industrial scale.",
   "Chemistry;Physics;Mathematics", "B.Tech/B.E. Chemical",
   "Process design;Reaction engineering;Plant safety;Simulation", "Aspen;MATLAB;DCS systems",
   5, 25, 4, 3, 0.75, 0.30, 0.15, "Mumbai;Vadodara;Chennai;Visakhapatnam",
   "Petroleum & Energy Engineering;Materials Science & Metallurgy;Pharmaceutical Research"),
  ("Aerospace Engineering", "Advanced Engineering", "flight mathematics precision curious ambitious",
   "Design aircraft, rockets and satellites.",
   "Physics;Mathematics", "B.Tech Aerospace/Aeronautical",
   "Aerodynamics;Propulsion;Structures;Simulation", "MATLAB;CFD tools;CAD",
   6, 25, 5, 4, 0.70, 0.20, 0.20, "Bengaluru;Hyderabad;Thiruvananthapuram",
   "Space Science & Careers;Mechanical Engineering;Defence Research & Development"),
  ("Automotive Engineering", "Advanced Engineering", "vehicles machines design hands-on innovation",
   "Build the vehicles of the EV era.",
   "Physics;Mathematics", "B.Tech Mechanical/Automobile",
   "Vehicle systems;EV powertrains;Testing & validation;CAD", "CATIA;MATLAB;CAN tools",
   4, 25, 3, 3, 0.80, 0.30, 0.15, "Pune;Chennai;Gurugram;Bengaluru",
   "Mechanical Engineering;Mechatronics Engineering;Renewable Energy Engineering"),
  ("Industrial & Production Engineering", "Manufacturing", "efficiency systems organization analytical practical",
   "Make factories faster, safer and less wasteful.",
   "Physics;Mathematics", "B.Tech Industrial/Production",
   "Process optimization;Lean manufacturing;Quality systems;Plant layout", "Excel;Simulation;ERP;Six Sigma",
   4, 20, 3, 3, 0.80, 0.40, 0.20, "Pune;Chennai;NCR;Ahmedabad",
   "Operations Management;Manufacturing & Quality Engineering;Mechanical Engineering"),
  ("Mechatronics Engineering", "Advanced Engineering", "robotics machines electronics programming building",
   "Blend mechanics, electronics and software into smart machines.",
   "Physics;Mathematics;Computer Science", "B.Tech Mechatronics",
   "Automation systems;Robotics;PLC programming;Sensors & actuators", "PLC;ROS;CAD;Arduino",
   5, 25, 4, 3, 0.75, 0.20, 0.25, "Pune;Bengaluru;Chennai",
   "Robotics & Automation;Mechanical Engineering;Embedded Systems & IoT"),
  ("Materials Science & Metallurgy", "Manufacturing", "materials chemistry research analytical lab",
   "Invent and improve the materials everything else is made from.",
   "Chemistry;Physics;Mathematics", "B.Tech Metallurgy/Materials",
   "Material characterization;Heat treatment;Failure analysis;Research methods", "SEM/XRD;Simulation;Lab equipment",
   5, 18, 4, 2, 0.70, 0.25, 0.20, "Jamshedpur;Pune;Hyderabad;Steel belts",
   "Chemical Engineering;Physics Research;Mining Engineering"),
  ("Mining Engineering", "Resources & Energy", "outdoors resources machines safety practical",
   "Extract the minerals modern life depends on — safely and responsibly.",
   "Physics;Mathematics;Chemistry", "B.Tech Mining",
   "Mine planning;Safety engineering;Drilling & blasting;Surveying", "Mine software;Surveying tools",
   5, 15, 4, 2, 0.65, 0.30, 0.05, "Jharkhand;Odisha;Chhattisgarh;Rajasthan",
   "Geology & Earth Sciences;Petroleum & Energy Engineering;Civil Engineering"),
  ("Petroleum & Energy Engineering", "Resources & Energy", "energy resources analytical field ambitious",
   "Find and produce oil, gas and the fuels in transition.",
   "Physics;Chemistry;Mathematics", "B.Tech Petroleum",
   "Reservoir engineering;Drilling;Production optimization;HSE", "Simulation;Field equipment",
   7, 30, 4, 3, 0.60, 0.25, 0.10, "Mumbai;Vadodara;Assam;Offshore",
   "Chemical Engineering;Renewable Energy Engineering;Geology & Earth Sciences"),
  ("Renewable Energy Engineering", "Resources & Energy", "sustainability energy innovation outdoors mission",
   "Build India's solar, wind and green-hydrogen future.",
   "Physics;Mathematics;Chemistry", "B.Tech EE/Mechanical + renewable specialization",
   "Solar/wind system design;Energy storage;Grid integration;Project execution", "PVsyst;MATLAB;SCADA",
   5, 25, 4, 3, 0.90, 0.20, 0.30, "Gujarat;Rajasthan;Tamil Nadu;Bengaluru",
   "Electrical & Electronics Engineering;Environmental Management & Sustainability;Climate & ESG Careers"),
  ("Marine & Naval Engineering", "Advanced Engineering", "sea machines travel discipline hands-on",
   "Engineer ships and their power plants — at sea and in the yard.",
   "Physics;Mathematics", "B.Tech Marine/Naval Architecture;Marine engineering institutes",
   "Ship systems;Engine operation;Maintenance;Safety at sea", "Engine room systems;CAD",
   6, 20, 4, 3, 0.70, 0.20, 0.05, "Mumbai;Visakhapatnam;Kochi;At sea",
   "Merchant Navy;Mechanical Engineering;Shipping & Port Management"),
  ("Instrumentation & Control Engineering", "Manufacturing", "precision systems automation analytical detail",
   "Automate and control industrial plants with sensors and control loops.",
   "Physics;Mathematics", "B.Tech Instrumentation/EIE",
   "Control systems;Sensor calibration;PLC/DCS;Process safety", "PLC;DCS;SCADA;Calibrators",
   5, 18, 3, 2, 0.75, 0.35, 0.20, "Vadodara;Chennai;Pune;Refinery belts",
   "Electrical & Electronics Engineering;Chemical Engineering;Robotics & Automation"),
  ("Manufacturing & Quality Engineering", "Manufacturing", "quality precision systems detail practical",
   "Own quality on the production line — from Six Sigma to ISO.",
   "Physics;Mathematics", "B.Tech Mechanical/Production",
   "Quality systems;Statistical process control;Root-cause analysis;Auditing", "Six Sigma;CMM;Excel;ERP",
   4, 15, 3, 2, 0.75, 0.45, 0.15, "Pune;Chennai;NCR;Industrial hubs",
   "Industrial & Production Engineering;Operations Management;Mechanical Engineering"),
  ("Semiconductor & VLSI", "Advanced Engineering", "chips electronics precision analytical emerging",
   "Design the chips India is investing billions to make at home.",
   "Physics;Mathematics", "B.Tech ECE + M.Tech VLSI (common)",
   "Digital design;Verification;Physical design;EDA workflows", "Verilog;SystemVerilog;EDA tools",
   8, 45, 5, 4, 0.90, 0.20, 0.50, "Bengaluru;Hyderabad;Noida;Ahmedabad",
   "Electronics & Communication Engineering;Embedded Systems & IoT;Physics Research"),
  ("Biomedical Engineering", "Advanced Engineering", "health technology innovation science building",
   "Engineer medical devices — where healthcare meets hardware.",
   "Physics;Biology;Mathematics", "B.Tech Biomedical",
   "Medical device design;Biomaterials;Regulatory basics;Testing", "CAD;LabVIEW;Embedded tools",
   4, 18, 4, 3, 0.75, 0.20, 0.30, "Bengaluru;Chennai;Mumbai;Hyderabad",
   "Radiology & Medical Imaging;Embedded Systems & IoT;Epidemiology & Medical Research"),
  ("Engineering Management", "Manufacturing", "leadership engineering organization communication planning",
   "Lead engineering teams and complex technical projects.",
   "Physics;Mathematics;Business Studies", "B.Tech + MBA/M.Tech;PMP certification",
   "Project management;Technical leadership;Budgeting;Risk management", "MS Project;Excel;ERP",
   8, 30, 3, 3, 0.80, 0.20, 0.40, "All engineering hubs",
   "Business Management;Construction Management;Operations Management"),
 ]),

 "science-research": ("Science & Research", "🔬",
  "Ask nature the hard questions — research careers across the physical, life and earth sciences.", [
  ("Physics Research", "Physical Sciences", "physics mathematics curious research analytical",
   "Probe how the universe works — from quantum systems to cosmology.",
   "Physics;Mathematics", "B.Sc Physics;+ M.Sc + PhD;IISER/IIT integrated",
   "Mathematical modelling;Experimentation;Scientific computing;Paper writing", "Python;MATLAB;Lab instruments;LaTeX",
   5, 25, 5, 3, 0.65, 0.10, 0.50, "Bengaluru;Mumbai;Pune;Kolkata",
   "Astronomy & Astrophysics;Mathematics & Statistics;Semiconductor & VLSI"),
  ("Chemistry & Materials Research", "Physical Sciences", "chemistry lab curious detail research",
   "Discover molecules and materials — from drugs to batteries.",
   "Chemistry;Physics;Mathematics", "B.Sc Chemistry;+ M.Sc + PhD",
   "Synthesis;Analytical techniques;Spectroscopy;Lab safety", "NMR;HPLC;Spectrometers;Python basics",
   5, 22, 4, 3, 0.70, 0.20, 0.20, "Pune;Hyderabad;Bengaluru;Mumbai",
   "Pharmaceutical Research;Materials Science & Metallurgy;Chemical Engineering"),
  ("Mathematics & Statistics", "Physical Sciences", "mathematics logic abstract analytical curious",
   "Do pure and applied mathematics — the language every science speaks.",
   "Mathematics;Physics", "B.Sc/B.Stat Mathematics/Statistics;ISI/CMI;+ M.Sc/PhD",
   "Proof & abstraction;Statistical modelling;Computation;Problem solving", "Python;R;LaTeX;Mathematica",
   6, 30, 4, 3, 0.75, 0.10, 0.70, "Kolkata;Chennai;Bengaluru;Delhi",
   "Data & Artificial Intelligence;Insurance & Actuarial Science;Physics Research"),
  ("Biology & Life Sciences Research", "Life Sciences", "biology curious lab research patience",
   "Study living systems — from molecules to ecosystems.",
   "Biology;Chemistry", "B.Sc Life Sciences;+ M.Sc + PhD;IISER",
   "Experimental design;Cell & molecular techniques;Data analysis;Writing", "PCR;Microscopy;R;Lab systems",
   5, 20, 4, 3, 0.70, 0.15, 0.30, "Bengaluru;Pune;Hyderabad;Delhi",
   "Biotechnology & Genetics;Microbiology & Immunology;Neuroscience"),
  ("Biotechnology & Genetics", "Life Sciences", "biology innovation lab analytical emerging",
   "Engineer biology — gene editing, vaccines and bio-manufacturing.",
   "Biology;Chemistry;Mathematics", "B.Tech/B.Sc Biotechnology;+ M.Sc/M.Tech",
   "Genetic engineering;Bioprocessing;Bioinformatics;Lab techniques", "CRISPR workflows;Bioreactors;Python/R",
   5, 25, 4, 4, 0.80, 0.20, 0.30, "Bengaluru;Hyderabad;Pune;Ahmedabad",
   "Biology & Life Sciences Research;Pharmaceutical Research;Data & Artificial Intelligence"),
  ("Astronomy & Astrophysics", "Physical Sciences", "space physics curious mathematics wonder",
   "Study stars, galaxies and the cosmos.",
   "Physics;Mathematics", "B.Sc Physics + M.Sc Astronomy + PhD",
   "Observation & data analysis;Modelling;Scientific computing;Instrumentation", "Python;Telescopes;Astropy",
   6, 25, 5, 3, 0.60, 0.10, 0.60, "Pune;Bengaluru;Nainital;Ooty",
   "Physics Research;Space Science & Careers;Data & Artificial Intelligence"),
  ("Environmental Science", "Earth & Environment", "environment outdoors research service analytical",
   "Understand and protect ecosystems, air and water.",
   "Biology;Chemistry;Geography", "B.Sc Environmental Science;+ M.Sc",
   "Field sampling;Environmental assessment;GIS;Report writing", "GIS;Sensors;Lab analysis;Excel",
   4, 18, 3, 3, 0.80, 0.15, 0.40, "Delhi;Bengaluru;State pollution boards",
   "Environmental Management & Sustainability;Climate & ESG Careers;Wildlife Conservation"),
  ("Geology & Earth Sciences", "Earth & Environment", "earth outdoors exploration analytical field",
   "Read the Earth — minerals, groundwater, earthquakes and energy.",
   "Geography;Physics;Chemistry", "B.Sc Geology;+ M.Sc/M.Tech",
   "Field mapping;Rock & mineral analysis;Geophysical surveying;GIS", "GIS;Remote sensing;Field kits",
   4, 15, 4, 2, 0.70, 0.15, 0.20, "Hyderabad;Dehradun;Kolkata;Field sites",
   "Mining Engineering;Oceanography & Meteorology;Petroleum & Energy Engineering"),
  ("Oceanography & Meteorology", "Earth & Environment", "weather sea climate analytical field curious",
   "Forecast weather and study oceans and climate systems.",
   "Physics;Geography;Mathematics", "B.Sc + M.Sc Oceanography/Atmospheric Science",
   "Climate modelling;Data assimilation;Field observation;Analysis", "Python;Climate models;Satellites",
   5, 15, 4, 2, 0.75, 0.15, 0.40, "Pune;Hyderabad;Goa;Chennai",
   "Environmental Science;Geology & Earth Sciences;Data & Artificial Intelligence"),
  ("Forensic Science", "Applied Sciences", "investigation detail science justice analytical",
   "Apply science to crime — evidence, DNA and digital traces.",
   "Chemistry;Biology;Physics", "B.Sc Forensic Science;+ M.Sc",
   "Evidence analysis;Toxicology;DNA techniques;Report & testimony", "Lab instruments;Fingerprint & DNA kits",
   4, 20, 3, 3, 0.70, 0.20, 0.10, "Delhi;Hyderabad;Gandhinagar;State labs",
   "Crime Scene Investigation;Medical Laboratory Science;Chemistry & Materials Research"),
  ("Microbiology & Immunology", "Life Sciences", "biology lab detail research health",
   "Study microbes and immunity — pandemics taught us why it matters.",
   "Biology;Chemistry", "B.Sc Microbiology;+ M.Sc/PhD",
   "Culturing & assays;Immunological techniques;Quality control;Analysis", "Microscopy;ELISA;PCR",
   4, 15, 3, 3, 0.75, 0.20, 0.20, "Pune;Hyderabad;Bengaluru;Chennai",
   "Biology & Life Sciences Research;Medical Laboratory Science;Pharmaceutical Research"),
  ("Neuroscience", "Life Sciences", "brain curious research analytical interdisciplinary",
   "Study the brain — biology's deepest frontier.",
   "Biology;Psychology;Mathematics", "B.Sc Life Sciences/Psychology + M.Sc Neuroscience + PhD",
   "Neuroimaging;Experimental design;Data analysis;Computational modelling", "EEG/fMRI;Python;MATLAB",
   6, 20, 5, 3, 0.65, 0.10, 0.40, "Bengaluru;Gurugram (NBRC);Mumbai",
   "Biology & Life Sciences Research;Clinical Psychology;Data & Artificial Intelligence"),
  ("Pharmaceutical Research", "Applied Sciences", "chemistry health lab innovation detail",
   "Discover and develop new medicines.",
   "Chemistry;Biology;Mathematics", "B.Pharm/B.Sc + M.Pharm/M.Sc;PhD for research roles",
   "Drug discovery;Clinical research;Regulatory affairs;Analytical methods", "HPLC;LIMS;Statistical tools",
   5, 25, 4, 3, 0.85, 0.25, 0.30, "Hyderabad;Ahmedabad;Mumbai;Bengaluru",
   "Pharmacy;Chemistry & Materials Research;Biotechnology & Genetics"),
  ("Space Science & Careers", "Physical Sciences", "space exploration mission mathematics ambitious",
   "Work on India's space programme — missions, satellites, launchers.",
   "Physics;Mathematics", "B.Tech (via IIST/GATE to ISRO);B.Sc + M.Sc Space Science",
   "Mission analysis;Satellite systems;Ground operations;Simulation", "MATLAB;Python;Mission software",
   6, 20, 5, 4, 0.75, 0.10, 0.20, "Bengaluru;Thiruvananthapuram;Ahmedabad;Sriharikota",
   "Aerospace Engineering;Astronomy & Astrophysics;Defence Research & Development"),
  ("Science Communication", "Applied Sciences", "writing science teaching creativity media",
   "Translate research into stories the public understands.",
   "Any Science;English", "Science degree + journalism/communication training",
   "Science writing;Visual explanation;Interviewing;Fact-checking", "Writing tools;Podcasting;Video basics",
   4, 12, 3, 2, 0.65, 0.25, 0.85, "Delhi;Bengaluru;Mumbai;Remote",
   "Journalism;Content Creation & New Media;Teaching (School)"),
  ("Data & Analytics Research", "Applied Sciences", "statistics research data mathematics analytical",
   "Push the methods of data science itself — in labs and R&D teams.",
   "Mathematics;Statistics;Computer Science", "B.Sc/B.Stat + M.Sc/M.Stat;PhD for research labs",
   "Statistical theory;Experiment design;ML research;Publication", "Python;R;PyTorch;LaTeX",
   8, 40, 5, 4, 0.85, 0.15, 0.80, "Bengaluru;Hyderabad;Kolkata;Remote",
   "Data & Artificial Intelligence;Mathematics & Statistics;Physics Research"),
 ]),

 "education-training": ("Education & Training", "🎓",
  "Teach, coach and design how people learn — the profession that creates all others.", [
  ("Teaching (School)", "Teaching", "teaching people patience communication service",
   "Shape young minds as a school teacher across subjects and grades.",
   "Any subjects;Education", "B.A./B.Sc + B.Ed;Integrated B.Ed;+ TET/CTET",
   "Lesson planning;Classroom management;Assessment;Mentoring", "Smart boards;LMS;Office tools",
   3, 12, 2, 3, 0.85, 0.10, 0.20, "Everywhere — every town needs teachers",
   "Higher Education & Professorship;Early Childhood Education;Curriculum & Instructional Design"),
  ("Higher Education & Professorship", "Teaching", "research teaching depth academia writing",
   "Teach and research at colleges and universities.",
   "Chosen discipline;English", "Master's + NET/PhD in your discipline",
   "Advanced teaching;Research & publication;Mentoring;Grant writing", "LaTeX;LMS;Research tools",
   6, 25, 4, 4, 0.70, 0.10, 0.40, "University towns;All states",
   "Teaching (School);Physics Research;Educational Leadership & Administration"),
  ("Early Childhood Education", "Teaching", "children patience creativity care play",
   "Give children their first and most important learning years.",
   "Home Science;Psychology;Any", "B.Ed (Nursery);ECCE diplomas;NTT",
   "Play-based pedagogy;Child development;Parent communication;Storytelling", "Learning materials;Activity design",
   2, 8, 2, 2, 0.80, 0.05, 0.20, "All cities;Preschool chains",
   "Teaching (School);Special Education;Child Welfare & Protection"),
  ("Special Education", "Teaching", "empathy patience care teaching inclusion",
   "Teach children with diverse learning needs — deeply human work.",
   "Psychology;Biology;Any", "B.Ed Special Education (RCI recognized)",
   "Individualized education plans;Assistive methods;Behaviour support;Family collaboration", "Assistive tech;Therapy tools",
   3, 10, 3, 2, 0.85, 0.05, 0.30, "Metro cities;Inclusive schools",
   "Occupational Therapy;Speech & Audiology;Counselling Psychology"),
  ("Educational Leadership & Administration", "Education Systems", "leadership organization education vision people",
   "Run schools and education systems — principal to policy.",
   "Any;Education", "B.Ed + M.Ed;Teaching experience + leadership training",
   "School management;Teacher development;Accreditation;Community relations", "ERP;Assessment systems",
   6, 15, 3, 3, 0.75, 0.10, 0.30, "All cities",
   "Teaching (School);Education Policy;Curriculum & Instructional Design"),
  ("Curriculum & Instructional Design", "Education Systems", "design learning creativity structure writing",
   "Design what and how students learn — courses, materials, assessments.",
   "Education;Psychology;Any", "Any degree + instructional design certification;M.Ed",
   "Learning design;Content development;Assessment design;Learner research", "Articulate;LMS;Figma basics",
   5, 15, 3, 3, 0.80, 0.25, 0.90, "Bengaluru;Mumbai;Delhi;Remote",
   "EdTech Content & Product;Technical Writing;Teaching (School)"),
  ("EdTech Content & Product", "Education Systems", "education technology creativity content innovation",
   "Build the apps and content powering digital learning.",
   "Any;Computer Science helpful", "Any degree + subject expertise;B.Ed helpful",
   "Content creation;Video pedagogy;Learning analytics;Community building", "Video tools;LMS;Analytics",
   5, 20, 3, 3, 0.75, 0.25, 0.90, "Bengaluru;Mumbai;Delhi;Remote",
   "Curriculum & Instructional Design;Content Creation & New Media;Product Management"),
  ("Career Counselling", "Guidance & Development", "listening empathy guidance people psychology",
   "Guide students through the exact decision this app helps with.",
   "Psychology;Any", "B.A./M.A. Psychology;Career counselling certification",
   "Psychometric interpretation;Guidance conversations;Pathway knowledge;Ethics", "Assessment tools;Counselling frameworks",
   4, 12, 3, 2, 0.80, 0.15, 0.80, "All cities;Online practice",
   "Counselling Psychology;Educational Psychology;Human Resources"),
  ("Corporate Training & L&D", "Guidance & Development", "teaching communication business people energy",
   "Teach professionals — upskilling is a permanent industry.",
   "Any;Business Studies", "Any degree + domain expertise;MBA HR for L&D roles",
   "Training delivery;Program design;Facilitation;Impact measurement", "LMS;Presentation tools;Survey tools",
   5, 15, 3, 3, 0.75, 0.20, 0.80, "All metros;Remote",
   "Human Resources;Curriculum & Instructional Design;Public Speaking & Coaching"),
  ("Language Teaching", "Teaching", "language communication culture patience teaching",
   "Teach English, foreign or Indian languages — in classrooms and online.",
   "English;Languages", "B.A. Language/Linguistics;CELTA/TEFL;JLPT/DELF etc.",
   "Language pedagogy;Curriculum use;Assessment;Cultural context", "Online teaching platforms;LMS",
   3, 10, 2, 3, 0.75, 0.20, 0.90, "Metros;Online worldwide",
   "Translation & Interpretation;Teaching (School);Content Creation & New Media"),
  ("Library & Information Science", "Education Systems", "organization knowledge detail service research",
   "Curate and manage knowledge — libraries, archives and digital collections.",
   "Any;English", "B.Lib.Sc + M.Lib.Sc",
   "Cataloguing;Information retrieval;Digital archiving;Reader services", "Library systems;Databases",
   3, 8, 2, 2, 0.60, 0.30, 0.30, "Universities;Public systems;Corporates",
   "Higher Education & Professorship;Teaching (School);Museum & Heritage Education"),
  ("Test Prep & Competitive Coaching", "Guidance & Development", "teaching subject-mastery competition energy communication",
   "Coach students for JEE, NEET, UPSC and beyond — a massive Indian industry.",
   "Your strongest subjects", "Any degree + exam mastery;Teaching experience",
   "Concept teaching;Problem-solving strategies;Motivation;Content design", "Recording setups;Test platforms",
   4, 30, 3, 4, 0.80, 0.20, 0.70, "Kota;Delhi;Hyderabad;Online",
   "Teaching (School);EdTech Content & Product;Test Prep Entrepreneurship"),
  ("Educational Psychology", "Guidance & Development", "psychology children research learning empathy",
   "Understand how children learn — and help when learning hurts.",
   "Psychology;Biology", "B.A./B.Sc Psychology + M.A. Educational Psychology",
   "Learning assessment;Intervention design;Research;Teacher consultation", "Assessment batteries;SPSS",
   4, 12, 3, 2, 0.75, 0.10, 0.50, "Metro cities;Schools & clinics",
   "Career Counselling;Clinical Psychology;Special Education"),
  ("Museum & Heritage Education", "Education Systems", "history culture curation storytelling detail",
   "Bring museums, monuments and archives to life for the public.",
   "History;Arts;Any", "B.A. History/Museology;M.A. Museology",
   "Curation;Exhibit design;Public programming;Conservation basics", "Archival systems;Exhibit tools",
   3, 8, 3, 2, 0.60, 0.10, 0.20, "Delhi;Mumbai;Kolkata;Heritage cities",
   "Heritage Conservation;Library & Information Science;Tour Guiding & Experience Design"),
  ("Online Tutoring & Micro-schooling", "Teaching", "teaching independence online entrepreneurship communication",
   "Teach directly to students worldwide — your own classroom, your rules.",
   "Your strongest subjects", "Any degree + subject mastery",
   "Online pedagogy;Student acquisition;Personalized teaching;Feedback", "Zoom;Whiteboard tools;Payment platforms",
   3, 15, 2, 3, 0.75, 0.25, 1.00, "Anywhere with internet",
   "Test Prep & Competitive Coaching;Language Teaching;EdTech Content & Product"),
  ("Education Policy", "Education Systems", "policy research education systems analytical",
   "Shape how India educates — NEP implementation, state reform, ed-research.",
   "Social Science;Economics;Education", "Any degree + MPP/M.A. Education;Development studies",
   "Policy analysis;Program evaluation;Stakeholder engagement;Writing", "Excel;Survey tools;Research databases",
   6, 15, 3, 3, 0.70, 0.10, 0.50, "Delhi;State capitals;Think tanks",
   "Public Policy & Governance;Economics & Policy Analysis;Educational Leadership & Administration"),
  ("Public Speaking & Coaching", "Guidance & Development", "communication confidence performance people energy",
   "Coach voices and minds — debate, communication and life skills.",
   "English;Any", "Any degree + certification/portfolio of results",
   "Speech coaching;Confidence building;Workshop design;Personal branding", "Recording tools;Social platforms",
   3, 12, 2, 3, 0.65, 0.15, 0.85, "Metros;Online",
   "Corporate Training & L&D;Content Creation & New Media;Career Counselling"),
  ("Test Prep Entrepreneurship", "Guidance & Development", "entrepreneurship education business teaching risk",
   "Build your own coaching institute or learning brand.",
   "Your strongest subjects;Business Studies", "Any degree + exam expertise",
   "Teaching at scale;Business building;Marketing;Team building", "Video platforms;Payment & CRM tools",
   0, 100, 3, 4, 0.70, 0.15, 0.70, "Any city;Online-first possible",
   "Entrepreneurship & Startups;Test Prep & Competitive Coaching;EdTech Content & Product"),
 ]),
}
