"""The validation pipeline: only validated knowledge enters the database.

Entities and relationships — whether imported from sources, derived by
heuristics or generated by the LLM — all pass through here. ERROR issues
reject the item; WARNING issues keep it but are reported so enrichment and
curation can act on them.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ...domain.knowledge_graph.ontology import NodeType
from ..models.entities import CandidateRelationship, CanonicalEntity
from ..normalizers.text import slugify
from .checks import (
    Severity,
    ValidationIssue,
    check_confidence,
    check_duplicates,
    check_relationship,
    check_required_fields,
    check_schema,
)


@dataclass(frozen=True, slots=True)
class EntityValidationReport:
    accepted: tuple[CanonicalEntity, ...] = field(default_factory=tuple)
    rejected: tuple[CanonicalEntity, ...] = field(default_factory=tuple)
    issues: tuple[ValidationIssue, ...] = field(default_factory=tuple)


@dataclass(frozen=True, slots=True)
class RelationshipValidationReport:
    accepted: tuple[CandidateRelationship, ...] = field(default_factory=tuple)
    rejected: tuple[CandidateRelationship, ...] = field(default_factory=tuple)
    issues: tuple[ValidationIssue, ...] = field(default_factory=tuple)


class ValidationPipeline:
    """Runs every check and splits input into accepted / rejected."""

    def __init__(self, min_confidence: float = 0.3) -> None:
        if not (0.0 <= min_confidence <= 1.0):
            raise ValueError("min_confidence must be within [0, 1]")
        self._min_confidence = min_confidence

    def validate_entities(
        self, entities: tuple[CanonicalEntity, ...]
    ) -> EntityValidationReport:
        all_issues: list[ValidationIssue] = list(check_duplicates(entities))
        rejected_names = {
            i.subject for i in all_issues if i.severity is Severity.ERROR
        }

        accepted: list[CanonicalEntity] = []
        rejected: list[CanonicalEntity] = []
        seen_slugs: set[tuple[NodeType, str]] = set()
        for entity in entities:
            issues = (
                check_required_fields(entity)
                + check_schema(entity)
                + check_confidence(entity, self._min_confidence)
            )
            all_issues.extend(issues)
            has_error = entity.canonical_name in rejected_names or any(
                i.severity is Severity.ERROR for i in issues
            )
            key = (entity.entity_type, entity.slug)
            if has_error or key in seen_slugs:
                rejected.append(entity)
            else:
                seen_slugs.add(key)
                accepted.append(entity)
        return EntityValidationReport(tuple(accepted), tuple(rejected), tuple(all_issues))

    def validate_relationships(
        self,
        relationships: tuple[CandidateRelationship, ...],
        entities: tuple[CanonicalEntity, ...],
    ) -> RelationshipValidationReport:
        known = {e.slug: e.entity_type for e in entities}
        for entity in entities:  # aliases resolve to their canonical entity
            for alias in entity.aliases:
                known.setdefault(slugify(alias), entity.entity_type)

        accepted: list[CandidateRelationship] = []
        rejected: list[CandidateRelationship] = []
        all_issues: list[ValidationIssue] = []
        seen: set[tuple[str, str, str]] = set()
        for rel in relationships:
            key = (
                rel.relationship.value,
                slugify(rel.source_name),
                slugify(rel.target_name),
            )
            if key in seen:
                continue  # exact duplicates are silently merged
            seen.add(key)
            issues = check_relationship(rel, known)
            all_issues.extend(issues)
            if any(i.severity is Severity.ERROR for i in issues):
                rejected.append(rel)
            else:
                accepted.append(rel)
        return RelationshipValidationReport(
            tuple(accepted), tuple(rejected), tuple(all_issues)
        )
